import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the UI preview (.preview/README.md)
    ".preview/app.js",
    // Agent skills installed from their providers (examples and helper scripts): not the app's code.
    ".agents/**",
    ".claude/**",
  ]),
]);

export default eslintConfig;
