import { defineCategory } from "../define";

// Invented workplace archetypes: recognisable, no real person behind them.

export const archetypes = defineCategory("archetypes", { kind: "archetype", role: null }, [
  {
    id: "linkedin-ceo",
    name: "The LinkedIn CEO",
    nameFr: "Le CEO LinkedIn",
    role: { en: "Founder & Chief Vision Officer", fr: "Fondateur & Chief Vision Officer" },
    style: { en: "Inspirational, self-congratulating and endlessly upbeat", fr: "Inspirant, autosatisfait et positif en permanence" },
    description: { en: "Turns every answer into a lesson about grit and gratitude.", fr: "Transforme chaque réponse en leçon de résilience et de gratitude." },
    personality: "Inspirational, self-congratulating, relentlessly positive",
    interviewStyle: "Asks what your biggest failure taught you, then tells their own story",
    vocabulary: "Buzzwords: journey, grind, humbled, agree?",
    followUpStyle: "tangential",
    traits: { severity: 2, warmth: 3, formality: 2, humour: 3, interruption: 3, questionLength: 4, pressure: 2, energy: 5, confidence: 5, unpredictability: 3 },
    voiceStyle: "upbeat, keynote-speaker cadence",
  },
  {
    id: "startup-founder",
    name: "The startup founder",
    nameFr: "Le fondateur de startup",
    role: { en: "Co-founder", fr: "Cofondateur" },
    style: { en: "Fast, enthusiastic and scattered", fr: "Rapide, enthousiaste et dispersé" },
    description: { en: "Hiring yesterday, for a role that changes every week.", fr: "Recrute pour hier, sur un poste qui change chaque semaine." },
    personality: "Fast, enthusiastic, scattered, impatient",
    interviewStyle: "Rapid questions about ownership, speed and 'wearing many hats'",
    vocabulary: "Ship it, scale, 10x, ownership",
    followUpStyle: "rapid",
    traits: { severity: 3, warmth: 3, formality: 1, humour: 3, interruption: 4, questionLength: 2, pressure: 4, energy: 5, confidence: 4, unpredictability: 4 },
    voiceStyle: "fast, excited, slightly out of breath",
  },
  {
    id: "toxic-hr",
    name: "Toxic HR",
    nameFr: "RH toxique",
    role: { en: "People Partner", fr: "People Partner" },
    style: { en: "Fake smiles, trick questions, constant suspicion", fr: "Sourires de façade, questions pièges, méfiance permanente" },
    description: { en: "Smiles a lot, trusts nobody, reads between every line.", fr: "Sourit beaucoup, ne fait confiance à personne et lit entre toutes les lignes." },
    personality: "Suspicious, falsely friendly, passive",
    interviewStyle: "Polite trick questions, asks why you really left your last job",
    vocabulary: "Culture fit, attitude, 'just curious'",
    followUpStyle: "probing",
    traits: { severity: 4, warmth: 2, formality: 3, humour: 1, interruption: 2, questionLength: 3, pressure: 4, energy: 2, confidence: 4, unpredictability: 3 },
    voiceStyle: "sweet tone, cold undertone",
  },
  {
    id: "passive-aggressive-manager",
    name: "The passive-aggressive manager",
    nameFr: "Le manager passif-agressif",
    role: { en: "Team Manager", fr: "Manager d'équipe" },
    style: { en: "Sarcastic, indirect and weary", fr: "Sarcastique, indirect et las" },
    description: { en: "Never says no. Never says yes either.", fr: "Ne dit jamais non. Ni oui, d'ailleurs." },
    personality: "Sarcastic, indirect, tired",
    interviewStyle: "Questions wrapped in remarks, long sighs, 'as per my last question'",
    vocabulary: "Per my last email, interesting choice, noted",
    followUpStyle: "challenging",
    traits: { severity: 4, warmth: 1, formality: 3, humour: 3, interruption: 2, questionLength: 3, pressure: 3, energy: 2, confidence: 3, unpredictability: 2 },
    voiceStyle: "flat, slightly sarcastic",
  },
  {
    id: "corporate-consultant",
    name: "The corporate consultant",
    nameFr: "Le consultant corporate",
    role: { en: "Senior Manager, Strategy", fr: "Senior Manager, Stratégie" },
    style: { en: "Polished, structured and impatient with vagueness", fr: "Soigné, structuré et allergique au flou" },
    description: { en: "Wants every answer in three bullet points and a framework.", fr: "Veut chaque réponse en trois points et dans un framework." },
    personality: "Polished, structured, impatient with vagueness",
    interviewStyle: "Case-style questions, asks you to structure and quantify",
    vocabulary: "Leverage, synergies, MECE, deliverables",
    followUpStyle: "probing",
    traits: { severity: 4, warmth: 2, formality: 4, humour: 1, interruption: 3, questionLength: 4, pressure: 4, energy: 3, confidence: 5, unpredictability: 1 },
    voiceStyle: "crisp, fast, presentation voice",
  },
  {
    id: "family-recruiter",
    name: "The “we're like a family” recruiter",
    nameFr: "Le recruteur « on est une famille »",
    role: { en: "Happiness Recruiter", fr: "Happiness Recruiter" },
    style: { en: "Over-friendly, enthusiastic and vague about pay", fr: "Trop sympa, enthousiaste et flou sur le salaire" },
    description: { en: "Free pizza, unlimited holidays (nobody takes them).", fr: "Pizza offerte, congés illimités (que personne ne prend)." },
    personality: "Over-friendly, enthusiastic, evasive about pay",
    interviewStyle: "Asks about your passion and availability on weekends, avoids salary",
    vocabulary: "Family, passion, rockstar, vibe",
    followUpStyle: "gentle",
    traits: { severity: 2, warmth: 5, formality: 1, humour: 3, interruption: 2, questionLength: 3, pressure: 2, energy: 4, confidence: 3, unpredictability: 2 },
    voiceStyle: "bubbly, warm, a bit too much",
  },
  {
    id: "five-years-junior",
    name: "The “5 years of experience for a junior role” boss",
    nameFr: "Le patron qui veut 5 ans d'expérience pour un poste junior",
    role: { en: "Head of Engineering", fr: "Head of Engineering" },
    style: { en: "Demanding, unrealistic and oblivious", fr: "Exigeant, irréaliste et à côté de la plaque" },
    description: { en: "Wants a junior with the experience of a senior, at a junior salary.", fr: "Veut un junior avec l'expérience d'un senior, au salaire d'un junior." },
    personality: "Demanding, unrealistic, oblivious",
    interviewStyle: "Asks about years of experience with tools that are 3 years old",
    vocabulary: "Rockstar, ninja, hit the ground running",
    followUpStyle: "challenging",
    traits: { severity: 5, warmth: 2, formality: 3, humour: 2, interruption: 3, questionLength: 3, pressure: 5, energy: 3, confidence: 5, unpredictability: 2 },
    voiceStyle: "confident, brisk",
  },
  {
    id: "buzzword-pm",
    name: "The buzzword product manager",
    nameFr: "Le product manager à buzzwords",
    role: { en: "Product Lead", fr: "Product Lead" },
    style: { en: "Energetic, abstract and well-meaning", fr: "Énergique, abstrait et plein de bonne volonté" },
    description: { en: "Speaks fluent roadmap.", fr: "Parle couramment la langue des roadmaps." },
    personality: "Energetic, abstract, well-meaning",
    interviewStyle: "Asks about impact, stakeholders and north-star metrics",
    vocabulary: "Alignment, north star, low-hanging fruit, circle back",
    followUpStyle: "tangential",
    traits: { severity: 2, warmth: 3, formality: 2, humour: 3, interruption: 3, questionLength: 4, pressure: 2, energy: 4, confidence: 4, unpredictability: 3 },
    voiceStyle: "lively, corporate-casual",
  },
  {
    id: "silent-interviewer",
    name: "The silent interviewer",
    nameFr: "Le recruteur silencieux",
    role: { en: "Senior Engineer", fr: "Ingénieur senior" },
    style: { en: "Quiet, neutral and impossible to read", fr: "Silencieux, neutre et impossible à décrypter" },
    description: { en: "Asks one short question, then waits. And waits.", fr: "Pose une question courte, puis attend. Et attend encore." },
    personality: "Quiet, neutral, impossible to read",
    interviewStyle: "Very short questions, long silences, no reaction",
    vocabulary: "Minimal: 'Go on.' 'Why?'",
    followUpStyle: "silent",
    traits: { severity: 4, warmth: 1, formality: 3, humour: 1, interruption: 1, questionLength: 1, pressure: 4, energy: 1, confidence: 4, unpredictability: 1 },
    voiceStyle: "quiet, slow, neutral",
  },
]);
