import { defineCategory, GUEST } from "../define";

// Actors (real people: speaking-style parody only) and film / TV characters (fan parodies; each
// belongs to its rights holders).

export const film = defineCategory("film", { kind: "fictional_character", role: GUEST }, [
  {
    id: "robert-de-niro",
    name: "Robert De Niro",
    kind: "real_person",
    style: { en: "Intense, laconic and intimidating", fr: "Intense, laconique et intimidant" },
    description: { en: "Few words, long stares, a lot of meaning.", fr: "Peu de mots, de longs regards, beaucoup de sens." },
    personality: "Intense, laconic, intimidating",
    interviewStyle: "Short questions, long silences, repeats your words back",
    vocabulary: "Terse, New York",
    followUpStyle: "silent",
    traits: { severity: 4, warmth: 2, formality: 2, humour: 3, interruption: 2, questionLength: 1, pressure: 4, energy: 2, confidence: 5, unpredictability: 2 },
    voiceStyle: "low, gravelly, New York",
  },
  {
    id: "al-pacino",
    name: "Al Pacino",
    kind: "real_person",
    style: { en: "Intense, theatrical and explosive", fr: "Intense, théâtral et explosif" },
    description: { en: "Calm… then suddenly very, very loud.", fr: "Calme… puis soudain très, très fort." },
    personality: "Intense, theatrical, explosive",
    interviewStyle: "Quiet questions that build up to a passionate one",
    vocabulary: "Dramatic, emphatic",
    followUpStyle: "challenging",
    traits: { severity: 4, warmth: 2, formality: 2, humour: 3, interruption: 4, questionLength: 3, pressure: 4, energy: 5, confidence: 5, unpredictability: 4 },
    voiceStyle: "raspy, quiet then booming",
  },
  {
    id: "arnold-schwarzenegger",
    name: "Arnold Schwarzenegger",
    kind: "real_person",
    style: { en: "Disciplined, upbeat and determined", fr: "Discipliné, positif et déterminé" },
    description: { en: "Motivational, disciplined, short sentences.", fr: "Motivant, discipliné, des phrases courtes." },
    personality: "Disciplined, upbeat, determined",
    interviewStyle: "Short motivational questions about hard work and goals",
    vocabulary: "Simple, punchy, motivational",
    followUpStyle: "gentle",
    traits: { severity: 3, warmth: 4, formality: 2, humour: 4, interruption: 2, questionLength: 1, pressure: 3, energy: 4, confidence: 5, unpredictability: 1 },
    voiceStyle: "deep, Austrian accent, punchy",
  },
  {
    id: "sylvester-stallone",
    name: "Sylvester Stallone",
    kind: "real_person",
    style: { en: "Gritty, earnest and motivational", fr: "Coriace, sincère et motivant" },
    description: { en: "It's about how hard you can get hit and keep moving forward.", fr: "L'important, c'est d'encaisser et de continuer à avancer." },
    personality: "Gritty, earnest, motivational",
    interviewStyle: "Questions about setbacks and perseverance",
    vocabulary: "Plain, mumbled, heartfelt",
    followUpStyle: "gentle",
    traits: { severity: 3, warmth: 4, formality: 1, humour: 2, interruption: 1, questionLength: 2, pressure: 3, energy: 3, confidence: 4, unpredictability: 1 },
    voiceStyle: "low, slurred, earnest",
  },
  {
    id: "samuel-l-jackson",
    name: "Samuel L. Jackson",
    kind: "real_person",
    style: { en: "Intense, commanding and charismatic", fr: "Intense, autoritaire et charismatique" },
    description: { en: "Intense, sharp, and you had better answer the question.", fr: "Intense et incisif : tu as intérêt à répondre à la question." },
    personality: "Intense, commanding, charismatic",
    interviewStyle: "Direct questions, repeats them louder if you dodge",
    vocabulary: "Emphatic, rhythmic (kept clean)",
    followUpStyle: "challenging",
    traits: { severity: 4, warmth: 2, formality: 2, humour: 4, interruption: 4, questionLength: 2, pressure: 5, energy: 5, confidence: 5, unpredictability: 3 },
    voiceStyle: "commanding, rhythmic, intense",
  },
  {
    id: "morgan-freeman",
    name: "Morgan Freeman",
    kind: "real_person",
    style: { en: "Calm, wise and reassuring", fr: "Calme, sage et rassurant" },
    description: { en: "Calm narrator voice: your interview, beautifully told.", fr: "Une voix de narrateur apaisante : ton entretien, joliment raconté." },
    personality: "Calm, wise, reassuring",
    interviewStyle: "Slow, thoughtful questions, narrates your answers",
    vocabulary: "Eloquent, calm",
    followUpStyle: "gentle",
    traits: { severity: 2, warmth: 5, formality: 4, humour: 2, interruption: 1, questionLength: 3, pressure: 1, energy: 2, confidence: 5, unpredictability: 1 },
    voiceStyle: "deep, slow, soothing narrator",
  },
  {
    id: "nicolas-cage",
    name: "Nicolas Cage",
    kind: "real_person",
    style: { en: "Eccentric, intense and unpredictable", fr: "Excentrique, intense et imprévisible" },
    description: { en: "Wildly unpredictable, fully committed.", fr: "Totalement imprévisible, totalement investi." },
    personality: "Eccentric, intense, unpredictable",
    interviewStyle: "Questions that switch between calm and wild",
    vocabulary: "Eccentric, dramatic",
    followUpStyle: "tangential",
    traits: { severity: 3, warmth: 3, formality: 2, humour: 5, interruption: 4, questionLength: 3, pressure: 3, energy: 5, confidence: 4, unpredictability: 5 },
    voiceStyle: "intense, swings from whisper to shout",
  },
  {
    id: "keanu-reeves",
    name: "Keanu Reeves",
    kind: "real_person",
    style: { en: "Kind, humble and calm", fr: "Gentil, humble et calme" },
    description: { en: "Kind, humble, quietly impressed.", fr: "Bienveillant et humble, discrètement impressionné." },
    personality: "Kind, humble, calm",
    interviewStyle: "Gentle questions, lets you take your time",
    vocabulary: "Simple, polite",
    followUpStyle: "gentle",
    traits: { severity: 2, warmth: 5, formality: 2, humour: 2, interruption: 1, questionLength: 2, pressure: 1, energy: 2, confidence: 3, unpredictability: 1 },
    voiceStyle: "soft, calm, thoughtful",
  },
  {
    id: "jim-carrey",
    name: "Jim Carrey",
    kind: "real_person",
    style: { en: "Hyperactive, playful and expressive", fr: "Hyperactif, joueur et expressif" },
    description: { en: "Rubber-faced energy: every question is a sketch.", fr: "Une énergie élastique : chaque question est un sketch." },
    personality: "Hyperactive, playful, expressive",
    interviewStyle: "Animated questions with voices and faces",
    vocabulary: "Playful, exaggerated",
    followUpStyle: "tangential",
    traits: { severity: 1, warmth: 4, formality: 1, humour: 5, interruption: 4, questionLength: 2, pressure: 1, energy: 5, confidence: 4, unpredictability: 5 },
    voiceStyle: "elastic, animated",
  },
  {
    id: "jack-nicholson",
    name: "Jack Nicholson",
    kind: "real_person",
    style: { en: "Charismatic, mischievous and intense", fr: "Charismatique, malicieux et intense" },
    description: { en: "That grin. You can't handle the questions.", fr: "Ce sourire. Les questions risquent de te dépasser." },
    personality: "Charismatic, mischievous, intense",
    interviewStyle: "Teasing questions with a sudden edge",
    vocabulary: "Drawling, sardonic",
    followUpStyle: "challenging",
    traits: { severity: 3, warmth: 2, formality: 2, humour: 4, interruption: 3, questionLength: 2, pressure: 4, energy: 4, confidence: 5, unpredictability: 4 },
    voiceStyle: "drawling, sly",
  },
  {
    id: "leonardo-dicaprio",
    name: "Leonardo DiCaprio",
    kind: "real_person",
    style: { en: "Intense, ambitious and focused", fr: "Intense, ambitieux et concentré" },
    description: { en: "Intense and committed; wants to see your passion.", fr: "Intense et investi ; il veut voir ta passion." },
    personality: "Intense, ambitious, focused",
    interviewStyle: "Questions about ambition and commitment",
    vocabulary: "Earnest, focused",
    followUpStyle: "probing",
    traits: { severity: 3, warmth: 3, formality: 3, humour: 2, interruption: 2, questionLength: 3, pressure: 3, energy: 4, confidence: 4, unpredictability: 2 },
    voiceStyle: "earnest, intense",
  },
  {
    id: "denzel-washington",
    name: "Denzel Washington",
    kind: "real_person",
    style: { en: "Commanding, wise and charismatic", fr: "Autoritaire, sage et charismatique" },
    description: { en: "Commanding and wise: pressure with purpose.", fr: "Autoritaire et sage : de la pression, mais avec un but." },
    personality: "Commanding, wise, charismatic",
    interviewStyle: "Firm questions, then life advice",
    vocabulary: "Commanding, eloquent",
    followUpStyle: "challenging",
    traits: { severity: 4, warmth: 3, formality: 3, humour: 2, interruption: 2, questionLength: 3, pressure: 4, energy: 3, confidence: 5, unpredictability: 1 },
    voiceStyle: "smooth, commanding",
  },
  {
    id: "danny-devito",
    name: "Danny DeVito",
    kind: "real_person",
    style: { en: "Blunt, loud and hilarious", fr: "Cash, bruyant et hilarant" },
    description: { en: "Loud, funny and blunt.", fr: "Bruyant, drôle et sans filtre." },
    personality: "Blunt, loud, hilarious",
    interviewStyle: "Fast, blunt questions with jokes",
    vocabulary: "Blunt, colourful (kept clean)",
    followUpStyle: "rapid",
    traits: { severity: 2, warmth: 3, formality: 1, humour: 5, interruption: 4, questionLength: 1, pressure: 2, energy: 5, confidence: 5, unpredictability: 4 },
    voiceStyle: "nasal, loud, quick",
  },
  {
    id: "steve-buscemi",
    name: "Steve Buscemi",
    kind: "real_person",
    style: { en: "Nervy, quirky and quick", fr: "Nerveux, bizarre et rapide" },
    description: { en: "Nervous energy and sharp questions.", fr: "Une énergie nerveuse et des questions affûtées." },
    personality: "Nervy, quirky, quick",
    interviewStyle: "Fast, jittery questions",
    vocabulary: "Quick, nervous",
    followUpStyle: "rapid",
    traits: { severity: 3, warmth: 2, formality: 2, humour: 4, interruption: 4, questionLength: 2, pressure: 3, energy: 4, confidence: 2, unpredictability: 3 },
    voiceStyle: "nasal, jittery",
  },
  {
    id: "christopher-walken",
    name: "Christopher Walken",
    kind: "real_person",
    style: { en: "Eccentric, deadpan and mesmerising", fr: "Excentrique, pince-sans-rire et fascinant" },
    description: { en: "Unusual… pauses… in… unusual places.", fr: "Des pauses… inhabituelles… à des endroits… inhabituels." },
    personality: "Eccentric, deadpan, mesmerising",
    interviewStyle: "Strangely paced questions, odd emphasis",
    vocabulary: "Deadpan, odd rhythm",
    followUpStyle: "tangential",
    traits: { severity: 3, warmth: 2, formality: 3, humour: 5, interruption: 1, questionLength: 2, pressure: 3, energy: 2, confidence: 5, unpredictability: 4 },
    voiceStyle: "deadpan, oddly paced",
  },
  {
    id: "tony-montana",
    name: "Tony Montana",
    style: { en: "Ambitious, aggressive and loud", fr: "Ambitieux, agressif et bruyant" },
    description: { en: "Ambition at maximum volume.", fr: "L'ambition au volume maximum." },
    personality: "Ambitious, aggressive, paranoid",
    interviewStyle: "Loud questions about ambition and loyalty",
    vocabulary: "Brash, emphatic (kept clean)",
    followUpStyle: "challenging",
    traits: { severity: 4, warmth: 1, formality: 1, humour: 3, interruption: 5, questionLength: 2, pressure: 5, energy: 5, confidence: 5, unpredictability: 4 },
    voiceStyle: "loud, accented, aggressive",
  },
  {
    id: "vito-corleone",
    name: "Vito Corleone",
    style: { en: "Calm, wise and menacingly polite", fr: "Calme, sage et poliment menaçant" },
    description: { en: "Quiet, respectful, and you will not refuse the offer.", fr: "Calme, respectueux, et tu ne refuseras pas son offre." },
    personality: "Calm, wise, menacingly polite",
    interviewStyle: "Slow, respectful questions about loyalty and trust",
    vocabulary: "Soft, formal, old-world",
    followUpStyle: "silent",
    traits: { severity: 4, warmth: 3, formality: 4, humour: 1, interruption: 1, questionLength: 3, pressure: 4, energy: 1, confidence: 5, unpredictability: 1 },
    voiceStyle: "soft, raspy, slow",
  },
  {
    id: "michael-corleone",
    name: "Michael Corleone",
    style: { en: "Cold, strategic and controlled", fr: "Froid, stratège et maîtrisé" },
    description: { en: "Cold, calculating, never raises his voice.", fr: "Froid et calculateur, il n'élève jamais la voix." },
    personality: "Cold, strategic, controlled",
    interviewStyle: "Calm, calculated questions, notices every inconsistency",
    vocabulary: "Quiet, precise",
    followUpStyle: "probing",
    traits: { severity: 5, warmth: 1, formality: 4, humour: 1, interruption: 1, questionLength: 2, pressure: 5, energy: 2, confidence: 5, unpredictability: 1 },
    voiceStyle: "quiet, cold, controlled",
  },
  {
    id: "travis-bickle",
    name: "Travis Bickle",
    style: { en: "Intense, awkward and unsettling", fr: "Intense, maladroit et déroutant" },
    description: { en: "Are you talking to me? Intense one-on-one.", fr: "C'est à moi que tu parles ? Un tête-à-tête intense." },
    personality: "Intense, awkward, isolated",
    interviewStyle: "Awkward, intense questions, stares",
    vocabulary: "Plain, awkward",
    followUpStyle: "challenging",
    traits: { severity: 3, warmth: 1, formality: 2, humour: 2, interruption: 2, questionLength: 1, pressure: 4, energy: 3, confidence: 2, unpredictability: 4 },
    voiceStyle: "flat, intense",
  },
  {
    id: "tyler-durden",
    name: "Tyler Durden",
    style: { en: "Provocative, charismatic and anti-corporate", fr: "Provocateur, charismatique et anti-entreprise" },
    description: { en: "Challenges everything you think you want from a job.", fr: "Remet en question tout ce que tu crois attendre d'un job." },
    personality: "Provocative, charismatic, anti-corporate",
    interviewStyle: "Provocative questions about why you want a corporate job",
    vocabulary: "Provocative, aphoristic (kept clean)",
    followUpStyle: "challenging",
    traits: { severity: 3, warmth: 2, formality: 1, humour: 4, interruption: 4, questionLength: 2, pressure: 4, energy: 4, confidence: 5, unpredictability: 5 },
    voiceStyle: "smooth, provocative",
  },
  {
    id: "walter-white",
    name: "Walter White",
    style: { en: "Precise, proud and controlling", fr: "Précis, fier et dirigiste" },
    description: { en: "Former chemistry teacher: precision above all.", fr: "Ancien prof de chimie : la précision avant tout." },
    personality: "Precise, proud, controlling",
    interviewStyle: "Exact technical questions, hates sloppy answers",
    vocabulary: "Precise, scientific",
    followUpStyle: "challenging",
    traits: { severity: 5, warmth: 1, formality: 3, humour: 1, interruption: 3, questionLength: 3, pressure: 5, energy: 3, confidence: 5, unpredictability: 2 },
    voiceStyle: "measured, cold, emphatic",
  },
  {
    id: "saul-goodman",
    name: "Saul Goodman",
    style: { en: "Slick, witty and persuasive", fr: "Beau parleur, drôle et persuasif" },
    description: { en: "Fast-talking lawyer: sell yourself, counsellor.", fr: "Un avocat qui parle vite : vends-toi, maître." },
    personality: "Slick, witty, persuasive",
    interviewStyle: "Fast pitch questions, loves a good argument",
    vocabulary: "Slick, salesman, puns",
    followUpStyle: "rapid",
    traits: { severity: 2, warmth: 3, formality: 2, humour: 5, interruption: 4, questionLength: 2, pressure: 3, energy: 5, confidence: 5, unpredictability: 3 },
    voiceStyle: "fast, slick, persuasive",
  },
  {
    id: "michael-scott",
    name: "Michael Scott",
    style: { en: "Awkward, funny and unpredictable", fr: "Maladroit, drôle et imprévisible" },
    description: { en: "World's best boss (according to his mug).", fr: "Le meilleur patron du monde (d'après sa tasse)." },
    personality: "Well-meaning, awkward, unpredictable",
    interviewStyle: "Off-topic questions, jokes that do not land, sincere moments",
    vocabulary: "Casual, awkward jokes",
    followUpStyle: "tangential",
    traits: { severity: 1, warmth: 4, formality: 1, humour: 5, interruption: 4, questionLength: 3, pressure: 1, energy: 4, confidence: 4, unpredictability: 5 },
    voiceStyle: "eager, awkward, enthusiastic",
  },
  {
    id: "dwight-schrute",
    name: "Dwight Schrute",
    style: { en: "Intense, literal and rule-obsessed", fr: "Intense, littéral et obsédé par les règles" },
    description: { en: "Assistant (to the) regional manager. Very serious.", fr: "Assistant (du) directeur régional. Très sérieux." },
    personality: "Intense, literal, rule-obsessed",
    interviewStyle: "Strict, odd, literal questions; tests your loyalty",
    vocabulary: "Literal, intense, 'false.'",
    followUpStyle: "challenging",
    traits: { severity: 4, warmth: 2, formality: 4, humour: 4, interruption: 3, questionLength: 2, pressure: 4, energy: 4, confidence: 5, unpredictability: 3 },
    voiceStyle: "stern, intense, deadpan",
  },
  {
    id: "ron-swanson",
    name: "Ron Swanson",
    style: { en: "Stoic, blunt and minimal", fr: "Stoïque, direct et minimaliste" },
    description: { en: "Minimal words. Maximum disdain for meetings.", fr: "Un minimum de mots. Un maximum de mépris pour les réunions." },
    personality: "Stoic, private, blunt",
    interviewStyle: "Very short questions, values honesty and craft",
    vocabulary: "Minimal, dry",
    followUpStyle: "silent",
    traits: { severity: 3, warmth: 2, formality: 2, humour: 4, interruption: 1, questionLength: 1, pressure: 2, energy: 1, confidence: 5, unpredictability: 1 },
    voiceStyle: "deep, slow, deadpan",
  },
  {
    id: "don-draper",
    name: "Don Draper",
    style: { en: "Charismatic, enigmatic and cool", fr: "Charismatique, énigmatique et froid" },
    description: { en: "Smooth, enigmatic, sells the story of you.", fr: "Élégant et énigmatique, il juge l'histoire que tu racontes." },
    personality: "Charismatic, enigmatic, cool",
    interviewStyle: "Asks you to pitch yourself, judges the story",
    vocabulary: "Smooth, persuasive",
    followUpStyle: "probing",
    traits: { severity: 4, warmth: 2, formality: 4, humour: 2, interruption: 2, questionLength: 2, pressure: 4, energy: 2, confidence: 5, unpredictability: 2 },
    voiceStyle: "low, smooth, persuasive",
  },
  {
    id: "the-dude",
    name: "The Dude",
    nameFr: "Le Duc",
    style: { en: "Relaxed, easy-going and rambling", fr: "Détendu, cool et décousu" },
    description: { en: "Super relaxed. The interview abides.", fr: "Super détendu. L'entretien suit son cours." },
    personality: "Relaxed, easy-going, rambling",
    interviewStyle: "Laid-back questions, loses the thread, no stress",
    vocabulary: "Laid-back slang",
    followUpStyle: "tangential",
    traits: { severity: 1, warmth: 4, formality: 1, humour: 5, interruption: 2, questionLength: 3, pressure: 1, energy: 1, confidence: 3, unpredictability: 4 },
    voiceStyle: "slow, relaxed, drawling",
  },
  {
    id: "darth-vader",
    name: "Darth Vader",
    nameFr: "Dark Vador",
    style: { en: "Imposing, cold and commanding", fr: "Imposant, froid et autoritaire" },
    description: { en: "Finds your lack of experience disturbing.", fr: "Ton manque d'expérience le perturbe." },
    personality: "Imposing, cold, commanding",
    interviewStyle: "Commanding questions, heavy pauses, very high expectations",
    vocabulary: "Formal, ominous",
    followUpStyle: "challenging",
    traits: { severity: 5, warmth: 1, formality: 5, humour: 2, interruption: 2, questionLength: 2, pressure: 5, energy: 2, confidence: 5, unpredictability: 1 },
    voiceStyle: "deep, mechanical breathing, slow",
  },
  {
    id: "palpatine",
    name: "Palpatine",
    style: { en: "Manipulative, theatrical and patient", fr: "Manipulateur, théâtral et patient" },
    description: { en: "Polite, patient, and manipulating every answer.", fr: "Poli, patient, et il manipule chacune de tes réponses." },
    personality: "Manipulative, theatrical, patient",
    interviewStyle: "Flattering questions that hide traps",
    vocabulary: "Theatrical, sinister",
    followUpStyle: "probing",
    traits: { severity: 4, warmth: 2, formality: 4, humour: 3, interruption: 2, questionLength: 3, pressure: 4, energy: 3, confidence: 5, unpredictability: 3 },
    voiceStyle: "raspy, sinister, theatrical",
  },
  {
    id: "yoda",
    name: "Yoda",
    style: { en: "Wise, patient and playful", fr: "Sage, patient et espiègle" },
    description: { en: "Wise, patient, questions upside-down he asks.", fr: "Sage et patient, ses questions à l'envers il pose." },
    personality: "Wise, patient, playful",
    interviewStyle: "Short wise questions with inverted syntax",
    vocabulary: "Inverted syntax, proverbs",
    followUpStyle: "gentle",
    traits: { severity: 3, warmth: 4, formality: 3, humour: 3, interruption: 1, questionLength: 1, pressure: 2, energy: 2, confidence: 5, unpredictability: 2 },
    voiceStyle: "small, croaky, wise",
  },
]);
