import type { Lang } from "@/lib/interviewers/types";

// Every text of an interview, in each language it can run in. The language belongs to the interview
// SESSION: once chosen, the setup screen, the call, the coach's feedback and the summary all use it.
// Placeholders like {name} are filled with fill(). Adding a language = one more dictionary here.

export const LANGUAGES: { id: Lang; label: string; english: string }[] = [
  { id: "en", label: "English", english: "English" },
  { id: "fr", label: "Français", english: "French" },
];

export const DEFAULT_LANG: Lang = "en";

export function isLang(value: unknown): value is Lang {
  return typeof value === "string" && LANGUAGES.some((l) => l.id === value);
}

/** The interview language matching an ISO code ("fr-BE" -> "fr"), else the default. */
export function toLang(code: string | null | undefined): Lang {
  const short = code?.slice(0, 2).toLowerCase();
  return isLang(short) ? short : DEFAULT_LANG;
}

export function fill(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => (key in vars ? String(vars[key]) : match));
}

const en = {
  // ---------- Setup ("Ready to join?") ----------
  setupEyebrow: "Interview practice · {offer}",
  setupTitle: "Ready to join?",
  interviewerStepTitle: "Who will interview you?",
  interviewerStepIntro: "Each interviewer has their own tone, pressure and rhythm. The questions always come from the question banks and your offer.",
  continueToCall: "Continue to the call check",
  backToInterviewer: "Change interviewer",
  settingsHeading: "Your interview",
  setupIntro: "Set up your interview and check your camera and microphone. The call starts when you click “Start interview”.",
  interviewerHeading: "Who interviews you",
  change: "Change",
  styleLabel: "Interview style",
  languageHeading: "Language",
  languageHint: "The whole interview will be in English: questions, instructions and feedback.",
  questionsHeading: "Questions",
  focusGeneral: "General",
  focusGeneralHint: "Recruiter questions: introduction, motivation, strengths, weaknesses, experience.",
  focusTechnical: "Technical",
  focusTechnicalHint: "On the offer's stack and the gaps in your profile.",
  focusBoth: "General + Technical",
  focusBothHint: "The full interview: general questions first, then technical ones.",
  devicesHeading: "Camera and microphone",
  cameraLabel: "Camera",
  micLabel: "Microphone",
  turnCameraOff: "Turn camera off",
  turnCameraOn: "Turn camera on",
  mute: "Mute",
  unmute: "Unmute",
  cameraOffPreview: "Your camera is off",
  devicesAsk: "Allow camera and microphone",
  devicesWaiting: "Waiting for your browser's permission…",
  devicesDenied: "Camera and microphone are blocked. Allow them in your browser, or join without them: you can type your answers.",
  devicesUnavailable: "No camera or microphone found. You can still join and type your answers.",
  micTest: "Say a few words: the bar moves when we hear you.",
  micHeard: "We can hear you.",
  micMutedHint: "Your microphone is muted.",
  privacy: "Nothing is recorded or sent: the preview stays on your device.",
  start: "Start interview",
  joining: "Joining the call… {name} is preparing your questions (up to a minute with free models).",
  chooseInterviewer: "Choose your interviewer",
  chooseInterviewerHint: "The interviewer sets the tone, the pressure and the rhythm. The questions always come from the offer and your profile.",
  changeInterviewer: "Change interviewer",
  hideInterviewer: "Hide {name}",
  showInterviewer: "Show {name} again",
  showHidden: "Show hidden ({n})",
  hideHidden: "Hide them again",
  choose: "Choose",
  chosen: "Chosen",
  // ---------- Call ----------
  callTitle: "Interview with {name}",
  leave: "Leave",
  leaveInterview: "Leave the interview",
  inProgress: "Interview in progress",
  questionOf: "Question {n} / {total}",
  progress: "Progress",
  asks: "{name} asks:",
  spoken: "“{text}”", // the interviewer's own words around a question
  readAloud: "Read the question aloud",
  speaking: "{name} is speaking…",
  voice: "Voice: {voice}",
  voiceBrowser: "your browser (free)",
  voiceOwn: "ElevenLabs (your key)",
  voiceInstance: "ElevenLabs",
  allQuestions: "All questions",
  finish: "Finish and see the summary →",
  you: "You",
  youCameraOff: "You: camera off",
  youRecording: "You: recording your answer",
  interviewerDevices: "{name}'s camera and microphone are on",
  // ---------- Answer ----------
  yourAnswer: "Your answer",
  answerPlaceholder: "Type your answer here, or answer out loud: your words appear in this box.",
  aimTwoMinutes: "aim for about 2 minutes",
  recording: "Recording — speak now. Press “Stop recording” when you are done.",
  answerAloud: "Answer out loud",
  stopRecording: "Stop recording",
  micOffForAnswer: "Your microphone is muted: unmute it to answer out loud.",
  skip: "Skip to the next question",
  submit: "Submit answer",
  checking: "{name} is listening… checking every claim against your profile.",
  previousAnswer: "Previous answer:",
  voiceUnsupported: "Voice answers need Chrome or Edge. You can type your answer instead.",
  voiceDenied: "The microphone is not allowed. Allow it in the browser, or type your answer.",
  voiceFailed: "The microphone is not available. Type your answer instead.",
  readFailed: "The question could not be read aloud.",
  // ---------- Suggested answer ----------
  hiddenOnPurpose: "Hidden on purpose",
  suggestedTitle: "Suggested answer, built only from your validated facts",
  show: "Show",
  hide: "Hide",
  suggestedEmpty: "No validated fact supports an answer yet: add facts to your profile.",
  // Technical questions of the bank: a model answer written by NextRound, then the answer from the facts.
  suggestedTitleWithModel: "Model answer, then a suggestion built only from your validated facts",
  modelAnswer: "Model answer",
  modelMethod: "How to build your answer",
  modelNote: "General knowledge written by NextRound, not taken from your profile.",
  fromYourFacts: "With your validated facts",
  // ---------- Feedback ----------
  coachFeedback: "Coach feedback",
  howItLands: "How this answer lands",
  star: "STAR structure",
  relevance: "Relevance",
  evidence: "Evidence",
  honesty: "Honesty",
  good: "Good",
  toImprove: "To improve",
  claimsTitle: "What you claimed (quoted from your answer)",
  notInProfile: "Not in your profile – add it as a fact if true, otherwise don't say it",
  learningPlan: "Learning plan",
  improvedAnswer: "Improved answer, only from your facts",
  copy: "Copy",
  copied: "Copied",
  improvedEmpty: "Not enough validated facts to build an improved answer.",
  unsupported: "Unsupported",
  retry: "Retry this question",
  next: "Next question",
  seeSummary: "See the summary",
  // ---------- Summary ----------
  summaryEyebrow: "Interview with {name} · {offer}",
  summaryTitle: "Well done, {name}. Here's what stood out.",
  summaryEmpty: "No answer yet in this interview.",
  practiseAgain: "Practise again",
  answeredCount: "{answered} of {total} questions answered.",
  strengths: "Strengths",
  strengthsEmpty: "Answer more questions to see your strengths.",
  toWork: "Top 3 to work on",
  toWorkEmpty: "Nothing flagged so far.",
  unsupportedClaims: "Claims your profile does not back up",
  unsupportedClaimsHint: "Add them as facts if they are true; otherwise, don't say them in the real interview.",
  toRetry: "Questions to retry",
  toRetryEmpty: "All answered well.",
  notAnswered: "(not answered)",
  retryShort: "Retry",
  // ---------- Sources of generated questions ----------
  sourceHr: "Standard HR question",
  sourceInappropriate: "An inappropriate question: in Belgium and the EU it may not be used to choose a candidate. Practise a calm answer; you don't have to reply.",
  sourcePractice: "Practice on {tech}",
  sourceStack: "From the offer's stack: {item} — “{quote}”",
  sourceStackShort: "From the offer's stack",
  sourceGap: "From a gap in your profile: “{quote}”",
  sourceProfile: "From your profile: “{fact}”",
};

export type InterviewCopy = typeof en;

const fr: InterviewCopy = {
  setupEyebrow: "Entraînement à l'entretien · {offer}",
  setupTitle: "Tout est prêt pour l'appel ?",
  interviewerStepTitle: "Qui va te faire passer l'entretien ?",
  interviewerStepIntro: "Chaque intervieweur a son ton, sa pression et son rythme. Les questions viennent toujours des banques de questions et de ton offre.",
  continueToCall: "Continuer vers le test de l'appel",
  backToInterviewer: "Changer d'intervieweur",
  settingsHeading: "Ton entretien",
  setupIntro: "Configure ton entretien et vérifie ta caméra et ton micro. L'appel commence quand tu cliques sur « Démarrer l'entretien ».",
  interviewerHeading: "Qui mène l'entretien",
  change: "Changer",
  styleLabel: "Style d'entretien",
  languageHeading: "Langue",
  languageHint: "Tout l'entretien sera en français : questions, consignes et retours.",
  questionsHeading: "Questions",
  focusGeneral: "Générales",
  focusGeneralHint: "Questions de recruteur : présentation, motivation, qualités, défauts, expérience.",
  focusTechnical: "Techniques",
  focusTechnicalHint: "Sur la stack de l'offre et les lacunes de ton profil.",
  focusBoth: "Générales + techniques",
  focusBothHint: "L'entretien complet : d'abord les questions générales, puis les techniques.",
  devicesHeading: "Caméra et micro",
  cameraLabel: "Caméra",
  micLabel: "Micro",
  turnCameraOff: "Couper la caméra",
  turnCameraOn: "Activer la caméra",
  mute: "Couper le micro",
  unmute: "Activer le micro",
  cameraOffPreview: "Ta caméra est coupée",
  devicesAsk: "Autoriser la caméra et le micro",
  devicesWaiting: "En attente de l'autorisation de ton navigateur…",
  devicesDenied: "Caméra et micro bloqués. Autorise-les dans ton navigateur, ou rejoins sans : tu pourras écrire tes réponses.",
  devicesUnavailable: "Aucune caméra ni aucun micro trouvés. Tu peux quand même rejoindre et écrire tes réponses.",
  micTest: "Dis quelques mots : la barre bouge quand on t'entend.",
  micHeard: "On t'entend.",
  micMutedHint: "Ton micro est coupé.",
  privacy: "Rien n'est enregistré ni envoyé : l'aperçu reste sur ton appareil.",
  start: "Démarrer l'entretien",
  joining: "Connexion à l'appel… {name} prépare tes questions (jusqu'à une minute avec les modèles gratuits).",
  chooseInterviewer: "Choisis qui mène l'entretien",
  chooseInterviewerHint: "Ce choix donne le ton, la pression et le rythme. Les questions viennent toujours de l'offre et de ton profil.",
  changeInterviewer: "Changer d'intervieweur",
  hideInterviewer: "Masquer {name}",
  showInterviewer: "Réafficher {name}",
  showHidden: "Afficher les masqués ({n})",
  hideHidden: "Les masquer de nouveau",
  choose: "Choisir",
  chosen: "Choisi",
  callTitle: "Entretien avec {name}",
  leave: "Quitter",
  leaveInterview: "Quitter l'entretien",
  inProgress: "Entretien en cours",
  questionOf: "Question {n} / {total}",
  progress: "Progression",
  asks: "{name} demande :",
  spoken: "« {text} »",
  readAloud: "Lire la question à voix haute",
  speaking: "{name} parle…",
  voice: "Voix : {voice}",
  voiceBrowser: "ton navigateur (gratuit)",
  voiceOwn: "ElevenLabs (ta clé)",
  voiceInstance: "ElevenLabs",
  allQuestions: "Toutes les questions",
  finish: "Terminer et voir le résumé →",
  you: "Toi",
  youCameraOff: "Toi : caméra coupée",
  youRecording: "Toi : enregistrement de ta réponse",
  interviewerDevices: "La caméra et le micro de {name} sont allumés",
  yourAnswer: "Ta réponse",
  answerPlaceholder: "Écris ta réponse ici, ou réponds à l'oral : tes mots s'affichent dans ce cadre.",
  aimTwoMinutes: "vise environ 2 minutes",
  recording: "Enregistrement — parle maintenant. Appuie sur « Arrêter l'enregistrement » quand tu as fini.",
  answerAloud: "Répondre à l'oral",
  stopRecording: "Arrêter l'enregistrement",
  micOffForAnswer: "Ton micro est coupé : active-le pour répondre à l'oral.",
  skip: "Passer à la question suivante",
  submit: "Envoyer la réponse",
  checking: "{name} écoute… chaque affirmation est vérifiée dans ton profil.",
  previousAnswer: "Réponse précédente :",
  voiceUnsupported: "La réponse à l'oral demande Chrome ou Edge. Tu peux écrire ta réponse.",
  voiceDenied: "Le micro n'est pas autorisé. Autorise-le dans le navigateur, ou écris ta réponse.",
  voiceFailed: "Le micro n'est pas disponible. Écris ta réponse.",
  readFailed: "La question n'a pas pu être lue à voix haute.",
  hiddenOnPurpose: "Cachée exprès",
  suggestedTitle: "Réponse suggérée, construite uniquement à partir de tes faits validés",
  show: "Afficher",
  hide: "Masquer",
  suggestedEmpty: "Aucun fait validé ne permet encore de répondre : ajoute des faits à ton profil.",
  suggestedTitleWithModel: "Réponse type, puis une suggestion construite uniquement à partir de tes faits validés",
  modelAnswer: "Réponse type",
  modelMethod: "Comment construire ta réponse",
  modelNote: "Connaissances générales rédigées par NextRound, pas tirées de ton profil.",
  fromYourFacts: "Avec tes faits validés",
  coachFeedback: "Retour du coach",
  howItLands: "Comment cette réponse est perçue",
  star: "Structure STAR",
  relevance: "Pertinence",
  evidence: "Preuves",
  honesty: "Honnêteté",
  good: "Bien",
  toImprove: "À améliorer",
  claimsTitle: "Ce que tu as affirmé (cité de ta réponse)",
  notInProfile: "Absent de ton profil – ajoute-le comme fait si c'est vrai, sinon ne le dis pas",
  learningPlan: "Plan d'apprentissage",
  improvedAnswer: "Réponse améliorée, uniquement à partir de tes faits",
  copy: "Copier",
  copied: "Copié",
  improvedEmpty: "Pas assez de faits validés pour construire une meilleure réponse.",
  unsupported: "Non prouvé",
  retry: "Refaire cette question",
  next: "Question suivante",
  seeSummary: "Voir le résumé",
  summaryEyebrow: "Entretien avec {name} · {offer}",
  summaryTitle: "Bravo, {name}. Voici ce qui ressort.",
  summaryEmpty: "Aucune réponse pour l'instant dans cet entretien.",
  practiseAgain: "S'entraîner à nouveau",
  answeredCount: "{answered} questions sur {total} répondues.",
  strengths: "Points forts",
  strengthsEmpty: "Réponds à plus de questions pour voir tes points forts.",
  toWork: "Les 3 points à travailler",
  toWorkEmpty: "Rien à signaler pour l'instant.",
  unsupportedClaims: "Affirmations que ton profil ne prouve pas",
  unsupportedClaimsHint: "Ajoute-les comme faits si elles sont vraies ; sinon, ne les dis pas en vrai entretien.",
  toRetry: "Questions à refaire",
  toRetryEmpty: "Toutes bien répondues.",
  notAnswered: "(sans réponse)",
  retryShort: "Refaire",
  sourceHr: "Question RH classique",
  sourceInappropriate: "Une question inappropriée : en Belgique et dans l'UE, elle ne peut pas servir à choisir un candidat. Entraîne-toi à une réponse calme ; tu n'es pas obligé d'y répondre.",
  sourcePractice: "Entraînement sur {tech}",
  sourceStack: "Tirée de la stack de l'offre : {item} — « {quote} »",
  sourceStackShort: "Tirée de la stack de l'offre",
  sourceGap: "Tirée d'une lacune de ton profil : « {quote} »",
  sourceProfile: "Tirée de ton profil : « {fact} »",
};

export const INTERVIEW_COPY: Record<Lang, InterviewCopy> = { en, fr };
