import type { QuestionEntry } from "./types";

// More technical questions, per technology id (same format and rules as the other bank files):
// junior level, answerable out loud, each with a model answer in the candidate's voice.

export const MORE_QUESTIONS: Record<string, readonly QuestionEntry[]> = {
  monitoring: [
    [
      "sli-slo", "concept",
      "What are an SLI, an SLO and an SLA?",
      "Que sont un SLI, un SLO et un SLA ?",
      "An SLI is a measure of service quality, for example the share of requests answered in under 300 ms. An SLO is the target we set on it, say 99.5% over thirty days. An SLA is the contract with customers, with consequences if it is missed; it is usually looser than the internal SLO, so we notice problems before breaking the contract.",
      "Un SLI est une mesure de la qualité du service, par exemple la part des requêtes servies en moins de 300 ms. Un SLO est l'objectif qu'on se fixe dessus, disons 99,5 % sur trente jours. Un SLA est le contrat avec les clients, avec des conséquences s'il n'est pas tenu ; il est en général plus souple que le SLO interne, pour qu'on voie les problèmes avant de rompre le contrat.",
    ],
    [
      "structured-logs", "best_practice",
      "What makes logs useful when you investigate a problem?",
      "Qu'est-ce qui rend les logs utiles quand on enquête sur un problème ?",
      "Structured logs, in JSON for example, so they can be searched by field; a level that means something; a request or correlation id to follow one request across services; and enough context, like the user or order id, without secrets or personal data. Too many logs hide the important ones, so I log decisions and errors, not every line.",
      "Des logs structurés, en JSON par exemple, pour pouvoir chercher par champ ; un niveau qui a du sens ; un identifiant de requête ou de corrélation pour suivre une requête à travers les services ; et assez de contexte, comme l'id de l'utilisateur ou de la commande, sans secret ni donnée personnelle. Trop de logs cachent les importants, donc je logue les décisions et les erreurs, pas chaque ligne.",
    ],
    [
      "slow-page", "troubleshoot",
      "Users say the app is slow since this morning. How do you find out why?",
      "Les utilisateurs trouvent l'application lente depuis ce matin. Comment {trouvez-vous|trouves-tu} pourquoi ?",
      "First I confirm with data: response times and error rates on the dashboards, and since when. Then I look at what changed around that time, a deploy, a config change, more traffic. I narrow down with traces to see which part is slow, the database, an external API or the code, and I check resources like CPU, memory and connection pools. If a deploy is the cause, rolling back is often the fastest fix while we analyse.",
      "D'abord je confirme avec des données : temps de réponse et taux d'erreur sur les tableaux de bord, et depuis quand. Ensuite je regarde ce qui a changé à ce moment-là, un déploiement, un changement de configuration, plus de trafic. Je réduis le périmètre avec les traces pour voir quelle partie est lente, la base de données, une API externe ou le code, et je vérifie les ressources comme le CPU, la mémoire et les pools de connexions. Si un déploiement est en cause, revenir en arrière est souvent le plus rapide pendant qu'on analyse.",
    ],
    [
      "health-check", "practice",
      "What should a health check endpoint check?",
      "Que doit vérifier un endpoint de health check ?",
      "I separate two checks. Liveness says the process is alive and should not be restarted, so it stays very simple. Readiness says the service can take traffic: it can reach its database and critical dependencies. It must be fast and must not trigger heavy work, otherwise the health check itself becomes a load problem.",
      "Je sépare deux vérifications. Le liveness dit que le processus est vivant et qu'il ne faut pas le redémarrer, donc il reste très simple. Le readiness dit que le service peut recevoir du trafic : il joint sa base de données et ses dépendances critiques. Il doit être rapide et ne pas lancer de gros traitements, sinon le health check devient lui-même un problème de charge.",
    ],
  ],
  agile: [
    [
      "retrospective", "concept",
      "What is a retrospective for, and what makes a good one?",
      "À quoi sert une rétrospective, et qu'est-ce qui en fait une bonne ?",
      "A retrospective is the team looking back at how it worked, not at what it built, to improve the next iteration. A good one is safe, so people say what really went wrong, and ends with one or two concrete actions with an owner, which we check at the next retro. Without actions it's just a complaint session.",
      "Une rétrospective, c'est l'équipe qui regarde comment elle a travaillé, pas ce qu'elle a construit, pour améliorer l'itération suivante. Une bonne rétro est un espace sûr, pour que chacun dise ce qui n'a vraiment pas marché, et se termine par une ou deux actions concrètes avec un responsable, qu'on vérifie à la rétro suivante. Sans actions, ce n'est qu'une séance de plaintes.",
    ],
    [
      "definition-of-done", "concept",
      "What is a 'definition of done'?",
      "Qu'est-ce que la « definition of done » ?",
      "It's the checklist the team agrees on for a task to count as finished: for example code reviewed, tests written and passing, documentation updated, deployed to staging. It avoids 'done but not really' and makes estimates and velocity meaningful, because everyone means the same thing by done.",
      "C'est la liste que l'équipe se fixe pour qu'une tâche compte comme terminée : par exemple code relu, tests écrits et qui passent, documentation à jour, déployé en recette. Ça évite le « fini mais pas vraiment » et donne du sens aux estimations et à la vélocité, parce que tout le monde met la même chose derrière « fini ».",
    ],
    [
      "scope-change", "practice",
      "In the middle of a sprint, the product owner adds an urgent task. What do you do?",
      "En plein sprint, le product owner ajoute une tâche urgente. Que {faites-vous|fais-tu} ?",
      "I don't just add it silently. With the team and the product owner we look at what it replaces: something of similar size leaves the sprint, or the sprint goal changes, and it's said openly. If urgent work keeps arriving, it's a signal to keep some capacity free or to review how priorities are set.",
      "Je ne l'ajoute pas en silence. Avec l'équipe et le product owner, on regarde ce qu'elle remplace : quelque chose de taille équivalente sort du sprint, ou l'objectif du sprint change, et on le dit clairement. Si l'urgent arrive sans arrêt, c'est le signal qu'il faut garder de la marge ou revoir la façon de fixer les priorités.",
    ],
    [
      "split-story", "practice",
      "A user story is too big for one sprint. How do you split it?",
      "Une user story est trop grosse pour un sprint. Comment la {découpez-vous|découpes-tu} ?",
      "I split it vertically, so each part still delivers something usable end to end, rather than by layer like 'database then API then UI'. For example by user path, by rule, or by starting with the simplest case and adding the variants later. Each piece should be testable and demonstrable on its own.",
      "Je la découpe verticalement, pour que chaque morceau apporte quelque chose d'utilisable de bout en bout, plutôt que par couche du genre « base, puis API, puis interface ». Par exemple par parcours utilisateur, par règle, ou en commençant par le cas le plus simple et en ajoutant les variantes ensuite. Chaque morceau doit pouvoir être testé et montré seul.",
    ],
  ],
  embedded: [
    [
      "polling-vs-interrupt", "compare",
      "Polling or interrupts: when do you use each?",
      "Polling ou interruptions : quand utiliser l'un ou l'autre ?",
      "Polling means the program checks a flag in a loop: simple and predictable, fine when the event is frequent or timing is relaxed, but it wastes CPU and power. An interrupt lets the hardware call a handler when the event happens: reactive and efficient, but the handler must be short, and shared data needs care. On battery devices, interrupts plus sleep modes are usually the way.",
      "Le polling, c'est vérifier un indicateur en boucle : simple et prévisible, bien quand l'événement est fréquent ou que le timing est souple, mais ça gaspille du CPU et de l'énergie. Une interruption laisse le matériel appeler une routine quand l'événement arrive : réactif et efficace, mais la routine doit être courte, et les données partagées demandent de l'attention. Sur un appareil sur batterie, interruptions et modes veille sont en général la bonne voie.",
    ],
    [
      "watchdog", "concept",
      "What is a watchdog timer for?",
      "À quoi sert un watchdog ?",
      "A watchdog is a hardware timer the program must reset regularly. If the software hangs and stops resetting it, the watchdog reboots the system. It protects a device that nobody can restart by hand. The trick is to reset it from a place that proves the main loop is really healthy, not from a timer interrupt that keeps running even when the rest is stuck.",
      "Un watchdog est un timer matériel que le programme doit relancer régulièrement. Si le logiciel se bloque et arrête de le relancer, le watchdog redémarre le système. Il protège un appareil que personne ne peut redémarrer à la main. L'astuce, c'est de le relancer depuis un endroit qui prouve que la boucle principale va vraiment bien, pas depuis une interruption de timer qui continue de tourner même quand le reste est bloqué.",
    ],
    [
      "uart-i2c-spi", "compare",
      "UART, I2C and SPI: what's the difference?",
      "UART, I2C et SPI : quelle différence ?",
      "UART is a simple point-to-point serial link with two wires and no clock, both sides agree on a speed; great for debugging consoles. I2C uses two wires, a clock and data, and addresses several devices on the same bus; slower, fine for sensors. SPI uses four wires with a chip select per device; faster and full duplex, good for screens or flash memory, but needs more pins.",
      "L'UART est une liaison série point à point simple, deux fils sans horloge, les deux côtés se mettent d'accord sur une vitesse ; parfait pour une console de debug. L'I2C utilise deux fils, une horloge et des données, et adresse plusieurs composants sur le même bus ; plus lent, bien pour des capteurs. Le SPI utilise quatre fils avec une sélection par composant ; plus rapide et full duplex, bien pour un écran ou une mémoire flash, mais il faut plus de broches.",
    ],
    [
      "debug-no-print", "troubleshoot",
      "Your firmware crashes and you have no screen or printf. How do you debug it?",
      "{Votre|Ton} firmware plante et {vous n'avez|tu n'as} ni écran ni printf. Comment {déboguez-vous|débogues-tu} ?",
      "I use what the hardware gives: a debugger through JTAG or SWD to stop the program and read registers and the stack, toggling a GPIO or a LED to mark where execution goes, a logic analyser on the pins, or logging to a buffer in RAM that I read afterwards. On a hard fault, the fault registers tell where it happened.",
      "J'utilise ce que le matériel offre : un débogueur en JTAG ou SWD pour arrêter le programme et lire les registres et la pile, faire changer une GPIO ou une LED pour marquer où passe l'exécution, un analyseur logique sur les broches, ou écrire des logs dans un buffer en RAM que je relis ensuite. En cas de hard fault, les registres de faute indiquent où ça s'est produit.",
    ],
  ],
  testing: [
    [
      "what-to-test", "best_practice",
      "You have little time. What do you test first?",
      "{Vous avez|Tu as} peu de temps. Que {testez-vous|testes-tu} en premier ?",
      "The things that cost the most when they break and break the most often: business rules like prices or rights, edge cases of the logic, and the main user path end to end. I test behaviour through the public interface, not private details, so the tests survive refactoring. Trivial getters can wait.",
      "Ce qui coûte le plus cher quand ça casse et ce qui casse le plus souvent : les règles métier comme les prix ou les droits, les cas limites de la logique, et le parcours principal de bout en bout. Je teste le comportement par l'interface publique, pas les détails internes, pour que les tests survivent au refactoring. Les getters triviaux peuvent attendre.",
    ],
    [
      "unit-vs-integration", "compare",
      "Unit tests or integration tests: what's the difference and why both?",
      "Tests unitaires ou tests d'intégration : quelle différence, et pourquoi les deux ?",
      "A unit test checks one piece of logic in isolation, it's fast and points exactly at the problem. An integration test checks that pieces work together for real, with a database or an API, it's slower but catches wiring mistakes the unit tests can't. Many fast unit tests plus a few integration tests on important paths give confidence without a slow suite.",
      "Un test unitaire vérifie un morceau de logique isolé, il est rapide et pointe exactement le problème. Un test d'intégration vérifie que les morceaux fonctionnent vraiment ensemble, avec une base de données ou une API ; il est plus lent mais attrape les erreurs de branchement que les tests unitaires ne voient pas. Beaucoup de tests unitaires rapides et quelques tests d'intégration sur les parcours importants donnent confiance sans une suite trop lente.",
    ],
    [
      "coverage", "concept",
      "Is 100% code coverage a good goal?",
      "100 % de couverture de code, c'est un bon objectif ?",
      "Not as a goal in itself. Coverage says which lines ran during tests, not whether the tests check anything. You can reach 100% with tests that assert nothing. I use it to find important code with no test at all, and I care more about good assertions on the critical logic than about the number.",
      "Pas comme objectif en soi. La couverture dit quelles lignes ont été exécutées pendant les tests, pas si les tests vérifient quelque chose. On peut atteindre 100 % avec des tests qui ne vérifient rien. Je m'en sers pour trouver du code important sans aucun test, et je tiens plus à de bonnes assertions sur la logique critique qu'au chiffre.",
    ],
    [
      "test-legacy", "practice",
      "You must change old code that has no tests. How do you proceed?",
      "{Vous devez|Tu dois} modifier du vieux code sans aucun test. Comment {procédez-vous|procèdes-tu} ?",
      "Before changing anything, I write characterization tests that capture what the code does today, even if it looks odd, on the part I will touch. Then I make small changes and run them each time. If the code is hard to test, I first extract a small seam, a function or an interface, with minimal risk. The goal is to change it safely, not to test everything.",
      "Avant de toucher quoi que ce soit, j'écris des tests de caractérisation qui capturent ce que le code fait aujourd'hui, même si ça paraît bizarre, sur la partie que je vais modifier. Ensuite je fais de petits changements et je relance ces tests à chaque fois. Si le code est difficile à tester, j'isole d'abord un point d'accroche, une fonction ou une interface, avec un risque minimal. Le but est de le modifier sans danger, pas de tout tester.",
    ],
  ],
  concurrency: [
    [
      "async-vs-threads", "compare",
      "Async code or threads: what's the difference?",
      "Code asynchrone ou threads : quelle différence ?",
      "Threads run work truly in parallel or interleaved by the system, each with its own stack; good for CPU-heavy work, but shared data needs locks. Async code usually runs on one thread and switches tasks while they wait for input or output, like network calls; great for many slow I/O operations with little overhead, but a CPU-heavy task blocks everything. I choose by what the program waits for.",
      "Les threads exécutent le travail vraiment en parallèle ou entrelacé par le système, chacun avec sa pile ; bien pour du calcul lourd, mais les données partagées demandent des verrous. Le code asynchrone tourne en général sur un seul thread et passe d'une tâche à l'autre pendant qu'elles attendent une entrée-sortie, comme un appel réseau ; parfait pour beaucoup d'opérations lentes avec peu de surcoût, mais une tâche qui calcule beaucoup bloque tout. Je choisis selon ce que le programme attend.",
    ],
    [
      "atomic", "concept",
      "What is an atomic operation, and why does i++ need care with threads?",
      "Qu'est-ce qu'une opération atomique, et pourquoi i++ demande-t-il de l'attention avec des threads ?",
      "An atomic operation happens all at once: no other thread can see it half done. i++ looks like one step but is three: read, add, write. Two threads can read the same value and both write the same result, so an increment is lost. The fix is an atomic type, like AtomicInteger or std::atomic, or a lock around the update.",
      "Une opération atomique se fait d'un bloc : aucun autre thread ne peut la voir à moitié faite. i++ a l'air d'une seule étape mais en fait trois : lire, ajouter, écrire. Deux threads peuvent lire la même valeur et écrire tous les deux le même résultat, donc un incrément est perdu. La solution : un type atomique, comme AtomicInteger ou std::atomic, ou un verrou autour de la mise à jour.",
    ],
    [
      "thread-pool", "concept",
      "Why use a thread pool instead of creating a thread per task?",
      "Pourquoi utiliser un pool de threads plutôt que créer un thread par tâche ?",
      "Creating a thread costs time and memory, and thousands of threads make the system spend its time switching between them. A pool keeps a fixed number of threads that take tasks from a queue: the cost is paid once, and the load is bounded. The size depends on the work: about the number of cores for CPU work, more for tasks that mostly wait.",
      "Créer un thread coûte du temps et de la mémoire, et des milliers de threads font passer le système son temps à basculer de l'un à l'autre. Un pool garde un nombre fixe de threads qui prennent les tâches dans une file : le coût est payé une fois et la charge est bornée. La taille dépend du travail : environ le nombre de cœurs pour du calcul, plus pour des tâches qui attendent surtout.",
    ],
    [
      "producer-consumer", "design",
      "How would you design a producer-consumer setup?",
      "Comment {concevriez-vous|concevrais-tu} un schéma producteur-consommateur ?",
      "Producers put items in a thread-safe queue and consumers take them out, so both sides work at their own pace. I use a bounded queue: when it is full, producers wait or drop, which protects memory. Consumers block while the queue is empty instead of spinning. For shutdown, a special stop item or a closed flag tells consumers to finish cleanly.",
      "Les producteurs déposent des éléments dans une file sûre entre threads et les consommateurs les retirent, chacun allant à son rythme. J'utilise une file bornée : quand elle est pleine, les producteurs attendent ou abandonnent, ce qui protège la mémoire. Les consommateurs se bloquent quand la file est vide au lieu de tourner à vide. Pour l'arrêt, un élément spécial ou un indicateur de fermeture dit aux consommateurs de finir proprement.",
    ],
  ],
  cloud: [
    [
      "iac", "concept",
      "Why describe infrastructure as code instead of clicking in the console?",
      "Pourquoi décrire l'infrastructure en code plutôt que cliquer dans la console ?",
      "Code is reviewed, versioned and repeatable: the same file creates the same environment for test and production, a change goes through a pull request, and we can see the history and roll back. Clicking is fast once but nobody remembers exactly what was done. Tools like Terraform or CloudFormation describe the desired state and apply only the difference.",
      "Le code se relit, se versionne et se rejoue : le même fichier crée le même environnement pour la recette et la production, un changement passe par une pull request, et on voit l'historique et on peut revenir en arrière. Cliquer est rapide une fois, mais personne ne se souvient exactement de ce qui a été fait. Des outils comme Terraform ou CloudFormation décrivent l'état voulu et n'appliquent que la différence.",
    ],
    [
      "serverless", "compare",
      "Serverless functions or a container: when would you choose each?",
      "Fonctions serverless ou conteneur : quand choisir l'un ou l'autre ?",
      "Serverless functions suit short, event-driven work with irregular traffic: no server to manage, you pay per call, it scales to zero. Limits are cold starts, maximum duration and less control. A container suits long-running services, steady traffic, special dependencies or when I want the same image everywhere. Many systems mix both.",
      "Les fonctions serverless conviennent à du travail court, déclenché par des événements, avec un trafic irrégulier : aucun serveur à gérer, on paie à l'appel, ça descend à zéro. Les limites : les démarrages à froid, une durée maximale et moins de contrôle. Un conteneur convient aux services qui tournent longtemps, au trafic régulier, aux dépendances particulières ou quand je veux la même image partout. Beaucoup de systèmes mélangent les deux.",
    ],
    [
      "public-bucket", "troubleshoot",
      "A storage bucket with user files turns out to be public. What do you do?",
      "Un bucket de stockage avec des fichiers d'utilisateurs se révèle public. Que {faites-vous|fais-tu} ?",
      "First, make it private immediately and block public access at the account level if possible. Then check the access logs to know what was read and by whom, and warn the people responsible, because leaked personal data may have to be reported. Then find how it happened and add a guard: a policy that forbids public buckets and a check in the infrastructure code.",
      "D'abord, le rendre privé immédiatement et bloquer l'accès public au niveau du compte si possible. Ensuite, consulter les logs d'accès pour savoir ce qui a été lu et par qui, et prévenir les responsables, car une fuite de données personnelles peut devoir être déclarée. Puis comprendre comment c'est arrivé et ajouter un garde-fou : une règle qui interdit les buckets publics et une vérification dans le code d'infrastructure.",
    ],
    [
      "high-availability", "design",
      "How do you make a web app keep running if one data centre goes down?",
      "Comment faire pour qu'une application web continue de tourner si un datacenter tombe ?",
      "Run several instances across availability zones behind a load balancer that stops sending traffic to unhealthy ones. Keep the instances stateless, with sessions and files in shared services. Use a managed database with a replica in another zone and automatic failover. Then test it: availability you never tested is a hope, not a design.",
      "Faire tourner plusieurs instances dans plusieurs zones de disponibilité derrière un load balancer qui arrête d'envoyer du trafic aux instances en mauvaise santé. Garder les instances sans état, avec les sessions et les fichiers dans des services partagés. Utiliser une base gérée avec un réplica dans une autre zone et une bascule automatique. Puis le tester : une disponibilité jamais testée est un espoir, pas une conception.",
    ],
  ],
  rest: [
    [
      "idempotence", "concept",
      "What does idempotent mean for an HTTP method, and why does it matter?",
      "Que veut dire idempotent pour une méthode HTTP, et pourquoi c'est important ?",
      "A method is idempotent when sending the same request several times has the same effect as sending it once. GET, PUT and DELETE are; POST usually is not. It matters for retries: after a timeout, a client can safely repeat an idempotent request. For POST, like a payment, we add an idempotency key so the server recognises a repeated request.",
      "Une méthode est idempotente quand envoyer la même requête plusieurs fois a le même effet que l'envoyer une fois. GET, PUT et DELETE le sont ; POST en général non. C'est important pour les nouvelles tentatives : après un timeout, un client peut répéter sans risque une requête idempotente. Pour un POST, comme un paiement, on ajoute une clé d'idempotence pour que le serveur reconnaisse une requête répétée.",
    ],
    [
      "put-vs-patch", "compare",
      "PUT or PATCH: what's the difference?",
      "PUT ou PATCH : quelle différence ?",
      "PUT replaces the whole resource with what is sent: fields left out are removed or reset, and it's idempotent. PATCH sends only the changes, to modify part of the resource; it's lighter, but its idempotence depends on how the changes are described. In practice I use PATCH for forms that change a few fields.",
      "PUT remplace toute la ressource par ce qui est envoyé : les champs absents sont supprimés ou remis à zéro, et c'est idempotent. PATCH n'envoie que les modifications, pour changer une partie de la ressource ; c'est plus léger, mais son idempotence dépend de la façon de décrire les changements. En pratique, j'utilise PATCH pour des formulaires qui modifient quelques champs.",
    ],
    [
      "errors", "best_practice",
      "How should an API return errors?",
      "Comment une API doit-elle renvoyer les erreurs ?",
      "With the right status code, 400 for invalid input, 401 when not signed in, 403 when not allowed, 404, 409 for a conflict, 500 for our own failure, and a consistent body: a stable error code, a readable message, and the field concerned for validation errors. Never a stack trace or internal details in production. Clients should be able to handle errors without parsing English sentences.",
      "Avec le bon code de statut, 400 pour une entrée invalide, 401 quand on n'est pas connecté, 403 quand on n'a pas le droit, 404, 409 pour un conflit, 500 pour notre propre panne, et un corps cohérent : un code d'erreur stable, un message lisible, et le champ concerné pour les erreurs de validation. Jamais de stack trace ni de détail interne en production. Les clients doivent pouvoir gérer les erreurs sans analyser des phrases.",
    ],
    [
      "rate-limit", "design",
      "How would you protect a public API from being overloaded by one client?",
      "Comment {protégeriez-vous|protégerais-tu} une API publique contre un client qui la surcharge ?",
      "With rate limiting per client, by API key or IP: a number of requests per window, for example a token bucket. Over the limit, answer 429 with a Retry-After header. Store the counters somewhere shared, like Redis, if there are several servers. Add authentication for expensive endpoints and size limits on requests.",
      "Avec une limite de débit par client, par clé d'API ou par IP : un nombre de requêtes par fenêtre de temps, par exemple un seau à jetons. Au-delà, répondre 429 avec un en-tête Retry-After. Stocker les compteurs dans un endroit partagé, comme Redis, s'il y a plusieurs serveurs. Ajouter une authentification pour les endpoints coûteux et des limites de taille sur les requêtes.",
    ],
  ],
  oop: [
    [
      "encapsulation-why", "concept",
      "Why make fields private and expose methods instead?",
      "Pourquoi rendre les champs privés et exposer des méthodes à la place ?",
      "So the object protects its own rules. If a balance can only change through deposit and withdraw, the object can refuse a negative amount, and no other code can put it in an invalid state. It also lets me change the inside later without breaking the code that uses it. Getters and setters for every field give none of that.",
      "Pour que l'objet protège ses propres règles. Si un solde ne peut changer que par deposit et withdraw, l'objet peut refuser un montant négatif, et aucun autre code ne peut le mettre dans un état invalide. Ça me permet aussi de changer l'intérieur plus tard sans casser le code qui l'utilise. Des getters et setters pour chaque champ n'apportent rien de tout ça.",
    ],
    [
      "interface-vs-abstract", "compare",
      "Interface or abstract class: when do you use each?",
      "Interface ou classe abstraite : quand utiliser l'une ou l'autre ?",
      "An interface describes what something can do, with no state, and a class can implement several; I use it to depend on a capability, like a PaymentGateway. An abstract class shares code and state between closely related classes, but a class has only one parent. By default I prefer interfaces, and I use an abstract class when subclasses really share an implementation.",
      "Une interface décrit ce qu'une chose sait faire, sans état, et une classe peut en implémenter plusieurs ; je l'utilise pour dépendre d'une capacité, comme un PaymentGateway. Une classe abstraite partage du code et de l'état entre des classes très proches, mais une classe n'a qu'un seul parent. Par défaut je préfère les interfaces, et j'utilise une classe abstraite quand les sous-classes partagent vraiment une implémentation.",
    ],
    [
      "polymorphism-example", "practice",
      "Give an example where polymorphism removes a big if/else.",
      "{Donnez|Donne} un exemple où le polymorphisme supprime un gros if/else.",
      "Say we compute shipping with if type == standard, else if express, else if pickup, repeated in several places. Instead, each shipping method is a class with a cost method, and the code just calls shipping.cost(order). Adding a new method means adding a class, not editing every if. That's the open-closed principle in practice.",
      "Imaginons qu'on calcule les frais de port avec if type == standard, else if express, else if retrait, répété à plusieurs endroits. À la place, chaque mode de livraison est une classe avec une méthode cost, et le code appelle simplement shipping.cost(order). Ajouter un mode, c'est ajouter une classe, pas modifier chaque if. C'est le principe ouvert-fermé en pratique.",
    ],
    [
      "dependency-injection", "concept",
      "What is dependency injection and what does it make easier?",
      "Qu'est-ce que l'injection de dépendances, et qu'est-ce qu'elle facilite ?",
      "Instead of a class creating what it needs, like its database client, it receives it, usually through the constructor. The class then depends on an interface, not a concrete implementation. It makes testing easy, because I can pass a fake, and it makes changing an implementation easy. Frameworks like Spring or Angular do the wiring, but the idea works by hand too.",
      "Au lieu qu'une classe crée ce dont elle a besoin, comme son client de base de données, elle le reçoit, en général par le constructeur. La classe dépend alors d'une interface, pas d'une implémentation concrète. Ça rend les tests faciles, car je peux passer une fausse implémentation, et ça facilite le changement d'implémentation. Des frameworks comme Spring ou Angular font le branchement, mais l'idée marche aussi à la main.",
    ],
  ],
  security: [
    [
      "sql-injection", "concept",
      "What is SQL injection and how do you prevent it?",
      "Qu'est-ce qu'une injection SQL, et comment l'éviter ?",
      "It's when user input is glued into an SQL query and changes its meaning, for example a login field containing ' OR 1=1 --. The fix is parameterized queries or an ORM, so input is always sent as data, never as SQL. On top, the database user should have only the rights the app needs.",
      "C'est quand une saisie de l'utilisateur est collée dans une requête SQL et en change le sens, par exemple un champ de connexion qui contient ' OR 1=1 --. La solution : des requêtes paramétrées ou un ORM, pour que la saisie soit toujours envoyée comme une donnée, jamais comme du SQL. En plus, l'utilisateur de la base ne doit avoir que les droits dont l'application a besoin.",
    ],
    [
      "authn-vs-authz", "compare",
      "Authentication or authorisation: what's the difference?",
      "Authentification ou autorisation : quelle différence ?",
      "Authentication checks who you are: password, OAuth, a token. Authorisation checks what you are allowed to do: can this user read this invoice? Many breaches come from good authentication with missing authorisation, for example changing an id in the URL to see someone else's data. Every request must check both, on the server.",
      "L'authentification vérifie qui tu es : mot de passe, OAuth, un jeton. L'autorisation vérifie ce que tu as le droit de faire : cet utilisateur peut-il lire cette facture ? Beaucoup de failles viennent d'une bonne authentification avec une autorisation oubliée, par exemple changer un id dans l'URL pour voir les données de quelqu'un d'autre. Chaque requête doit vérifier les deux, côté serveur.",
    ],
    [
      "validate-input", "best_practice",
      "Where should you validate user input, client or server?",
      "Où faut-il valider les saisies des utilisateurs, côté client ou côté serveur ?",
      "Both, for different reasons. Validation in the browser gives fast feedback and a better experience. Validation on the server is the real protection, because anyone can bypass the browser and send any request. I validate type, format and length with a schema on the server, and I encode output depending on where it's displayed.",
      "Les deux, pour des raisons différentes. La validation dans le navigateur donne un retour rapide et une meilleure expérience. La validation côté serveur est la vraie protection, car n'importe qui peut contourner le navigateur et envoyer n'importe quelle requête. Je valide le type, le format et la longueur avec un schéma côté serveur, et j'encode les sorties selon l'endroit où elles sont affichées.",
    ],
    [
      "dependencies", "practice",
      "How do you deal with vulnerabilities in your dependencies?",
      "Comment {gérez-vous|gères-tu} les failles dans {vos|tes} dépendances ?",
      "I scan them automatically, with npm audit, Dependabot or an equivalent in CI, and I read each alert: is the vulnerable code actually reachable in our use? Critical, reachable ones are fixed first by upgrading. I also keep dependencies few and maintained, and commit the lockfile so builds are reproducible.",
      "Je les analyse automatiquement, avec npm audit, Dependabot ou un équivalent dans la CI, et je lis chaque alerte : le code vulnérable est-il vraiment atteignable dans notre usage ? Les failles critiques et atteignables sont corrigées en premier, par une mise à jour. Je garde aussi peu de dépendances, et des dépendances maintenues, et je versionne le lockfile pour que les builds soient reproductibles.",
    ],
  ],
  vue: [
    [
      "composition-vs-options", "compare",
      "Composition API or Options API: what's the difference?",
      "Composition API ou Options API : quelle différence ?",
      "The Options API organises a component by type of option: data, methods, computed, watch. The Composition API, with setup or script setup, organises code by feature, with ref, reactive and computed, and lets you extract logic into reusable composables. For bigger components and TypeScript, I prefer the Composition API.",
      "L'Options API organise un composant par type d'option : data, methods, computed, watch. La Composition API, avec setup ou script setup, organise le code par fonctionnalité, avec ref, reactive et computed, et permet d'extraire la logique dans des composables réutilisables. Pour des composants plus gros et avec TypeScript, je préfère la Composition API.",
    ],
    [
      "v-if-v-show", "compare",
      "v-if or v-show: when do you use each?",
      "v-if ou v-show : quand utiliser l'un ou l'autre ?",
      "v-if really adds or removes the element from the DOM, and its children are created or destroyed; it's cheaper when the condition rarely changes. v-show always renders the element and only toggles CSS display; it's better for something toggled often, like a dropdown. Also, v-if on a component resets its state.",
      "v-if ajoute ou retire vraiment l'élément du DOM, et ses enfants sont créés ou détruits ; c'est moins coûteux quand la condition change rarement. v-show rend toujours l'élément et change seulement son display CSS ; c'est mieux pour quelque chose qu'on affiche et masque souvent, comme un menu déroulant. Et v-if sur un composant remet son état à zéro.",
    ],
    [
      "state-store", "design",
      "When do you need a store like Pinia instead of props and events?",
      "Quand faut-il un store comme Pinia plutôt que des props et des événements ?",
      "When several distant components share the same state, like the signed-in user or a cart, and passing props through many levels becomes painful. Pinia gives one place for that state with actions and devtools. For state used by one component and its children, props and events stay simpler.",
      "Quand plusieurs composants éloignés partagent le même état, comme l'utilisateur connecté ou un panier, et que faire passer des props sur plusieurs niveaux devient pénible. Pinia donne un seul endroit pour cet état, avec des actions et des outils de debug. Pour un état utilisé par un composant et ses enfants, les props et les événements restent plus simples.",
    ],
  ],
  go: [
    [
      "channels", "concept",
      "What are channels for in Go?",
      "À quoi servent les channels en Go ?",
      "Channels let goroutines send values to each other safely: one sends, another receives, and the channel synchronises them. Go's idea is to share memory by communicating instead of communicating by sharing memory. A buffered channel lets the sender continue up to its capacity; select waits on several channels at once, for example with a timeout.",
      "Les channels permettent aux goroutines de s'envoyer des valeurs en toute sécurité : l'une envoie, l'autre reçoit, et le channel les synchronise. L'idée de Go : partager la mémoire en communiquant plutôt que communiquer en partageant la mémoire. Un channel avec buffer laisse l'émetteur continuer jusqu'à sa capacité ; select attend sur plusieurs channels à la fois, par exemple avec un timeout.",
    ],
    [
      "defer", "concept",
      "What does defer do, and what do you use it for?",
      "Que fait defer, et à quoi {vous sert-il|te sert-il} ?",
      "defer schedules a call to run when the surrounding function returns, even after an error or a panic. I use it to release resources right after acquiring them: defer file.Close(), defer mu.Unlock(). Deferred calls run in reverse order, and their arguments are evaluated when defer is written, not at the end.",
      "defer programme un appel qui s'exécutera quand la fonction englobante se termine, même après une erreur ou un panic. Je l'utilise pour libérer une ressource juste après l'avoir prise : defer file.Close(), defer mu.Unlock(). Les appels différés s'exécutent dans l'ordre inverse, et leurs arguments sont évalués au moment du defer, pas à la fin.",
    ],
    [
      "context", "practice",
      "What is context.Context used for in a Go server?",
      "À quoi sert context.Context dans un serveur Go ?",
      "It carries a deadline, a cancellation signal and request-scoped values through the call chain. When the client disconnects or a timeout passes, the context is cancelled and every function that respects it, database queries, HTTP calls, stops early. I pass it as the first argument and never store it in a struct.",
      "Il transporte une échéance, un signal d'annulation et des valeurs liées à la requête tout au long de la chaîne d'appels. Quand le client se déconnecte ou qu'un timeout est dépassé, le contexte est annulé et chaque fonction qui le respecte, requêtes en base, appels HTTP, s'arrête tôt. Je le passe en premier argument et je ne le stocke jamais dans une struct.",
    ],
  ],
  rust: [
    [
      "lifetimes", "concept",
      "What are lifetimes in Rust?",
      "Que sont les lifetimes en Rust ?",
      "A lifetime is how long a reference is valid. The compiler checks that no reference outlives the data it points to, so dangling pointers are impossible. Most of the time lifetimes are inferred; I write them, like 'a, when a function returns a reference and the compiler needs to know which input it comes from.",
      "Une lifetime, c'est la durée pendant laquelle une référence est valide. Le compilateur vérifie qu'aucune référence ne vit plus longtemps que la donnée qu'elle pointe, donc les pointeurs pendants sont impossibles. La plupart du temps elles sont déduites ; je les écris, comme 'a, quand une fonction renvoie une référence et que le compilateur doit savoir de quelle entrée elle vient.",
    ],
    [
      "traits", "concept",
      "What is a trait in Rust?",
      "Qu'est-ce qu'un trait en Rust ?",
      "A trait defines behaviour that types can implement, a bit like an interface: for example Display to print a type or Iterator to loop over it. Functions can accept any type implementing a trait, through generics, resolved at compile time, or through dyn Trait, resolved at runtime. Traits can also provide default methods.",
      "Un trait définit un comportement que des types peuvent implémenter, un peu comme une interface : par exemple Display pour afficher un type ou Iterator pour le parcourir. Une fonction peut accepter n'importe quel type qui implémente un trait, par des génériques, résolus à la compilation, ou par dyn Trait, résolu à l'exécution. Un trait peut aussi fournir des méthodes par défaut.",
    ],
    [
      "clone-vs-borrow", "best_practice",
      "The borrow checker complains and you add .clone() everywhere. Is that okay?",
      "Le borrow checker se plaint et {vous ajoutez|tu ajoutes} .clone() partout. Est-ce une bonne idée ?",
      "Sometimes a clone is the right, simple answer, for small data or to get unstuck. But cloning everywhere hides a design question and costs memory and time. I first try to borrow instead, to restructure so ownership is clear, or to use Rc or Arc when data really has several owners. Clone on purpose, not by reflex.",
      "Parfois un clone est la bonne réponse, simple, pour une petite donnée ou pour se débloquer. Mais cloner partout cache une question de conception et coûte de la mémoire et du temps. J'essaie d'abord d'emprunter, de restructurer pour que la propriété soit claire, ou d'utiliser Rc ou Arc quand une donnée a vraiment plusieurs propriétaires. Cloner par choix, pas par réflexe.",
    ],
  ],
  nextjs: [
    [
      "server-actions", "concept",
      "What are server actions in Next.js, and what must you never forget in them?",
      "Que sont les server actions dans Next.js, et que ne faut-il jamais oublier dedans ?",
      "A server action is a function that runs on the server and that a form or a component can call directly, without writing an API route. It's still a public endpoint: anyone can call it with any input. So each action must check the session, check that the user may touch this data, and validate its input, for example with zod.",
      "Une server action est une fonction qui s'exécute sur le serveur et qu'un formulaire ou un composant peut appeler directement, sans écrire de route d'API. C'est quand même un point d'entrée public : n'importe qui peut l'appeler avec n'importe quelle entrée. Chaque action doit donc vérifier la session, vérifier que l'utilisateur a le droit de toucher ces données, et valider son entrée, par exemple avec zod.",
    ],
    [
      "caching", "troubleshoot",
      "You updated data but the page still shows the old version. What do you check?",
      "{Vous avez|Tu as} mis à jour des données mais la page affiche encore l'ancienne version. Que {vérifiez-vous|vérifies-tu} ?",
      "Caching, at each level: whether the page is static or dynamic, whether the data fetch is cached, and whether the mutation revalidates, with revalidatePath or revalidateTag after the change, or router.refresh on the client. I also check the CDN and the browser cache. Reading the version's docs matters, because the default caching rules have changed between versions.",
      "La mise en cache, à chaque niveau : si la page est statique ou dynamique, si la récupération des données est mise en cache, et si la mutation revalide, avec revalidatePath ou revalidateTag après le changement, ou router.refresh côté client. Je vérifie aussi le CDN et le cache du navigateur. Lire la documentation de la version compte, car les règles de cache par défaut ont changé d'une version à l'autre.",
    ],
  ],
  angular: [
    [
      "signals", "concept",
      "What are signals in Angular and why were they added?",
      "Que sont les signals dans Angular, et pourquoi ont-ils été ajoutés ?",
      "A signal is a reactive value: reading it in a template or a computed registers a dependency, and setting it updates exactly what depends on it. They make change detection more precise than checking the whole component tree, and simpler than RxJS for local state. Observables are still the tool for streams of events, like HTTP or user input over time.",
      "Un signal est une valeur réactive : la lire dans un template ou un computed enregistre une dépendance, et la modifier met à jour exactement ce qui en dépend. Ils rendent la détection de changements plus précise que la vérification de tout l'arbre de composants, et plus simple que RxJS pour l'état local. Les Observables restent l'outil pour les flux d'événements, comme le HTTP ou les saisies dans le temps.",
    ],
    [
      "unsubscribe", "troubleshoot",
      "A component keeps reacting after it was destroyed. What is probably wrong?",
      "Un composant continue de réagir après avoir été détruit. Qu'est-ce qui cloche probablement ?",
      "A subscription that was never closed: the observable keeps calling the component, which leaks memory and can cause odd bugs. The fixes: the async pipe in the template, which unsubscribes automatically, takeUntilDestroyed, or unsubscribing in ngOnDestroy. HTTP calls complete on their own, but intervals, router events or store selections don't.",
      "Un abonnement jamais fermé : l'observable continue d'appeler le composant, ce qui fait fuir la mémoire et peut causer des bugs étranges. Les solutions : le pipe async dans le template, qui se désabonne tout seul, takeUntilDestroyed, ou se désabonner dans ngOnDestroy. Les appels HTTP se terminent seuls, mais pas les intervalles, les événements du routeur ou les sélections du store.",
    ],
  ],
  redis: [
    [
      "data-types", "concept",
      "Which Redis data types do you know, and what is each one good for?",
      "Quels types de données Redis {connaissez-vous|connais-tu}, et à quoi sert chacun ?",
      "Strings for simple values and counters with INCR; hashes for an object's fields, like a session; lists for queues; sets for unique members, like tags; sorted sets for rankings and time-ordered data, like a leaderboard. Choosing the right type often removes a lot of application code.",
      "Les strings pour les valeurs simples et les compteurs avec INCR ; les hashes pour les champs d'un objet, comme une session ; les lists pour des files ; les sets pour des membres uniques, comme des tags ; les sorted sets pour des classements et des données ordonnées dans le temps, comme un leaderboard. Choisir le bon type évite souvent beaucoup de code applicatif.",
    ],
    [
      "ttl", "best_practice",
      "Why set an expiry on cached keys?",
      "Pourquoi mettre une expiration sur les clés en cache ?",
      "So stale data disappears on its own even if an invalidation is missed, and so memory doesn't fill with keys nobody reads. I choose the TTL from how fresh the data must be. Adding a little randomness to TTLs avoids many keys expiring at the same moment and all hitting the database together.",
      "Pour que les données périmées disparaissent toutes seules même si une invalidation est oubliée, et pour que la mémoire ne se remplisse pas de clés que personne ne lit. Je choisis la durée selon la fraîcheur nécessaire. Ajouter un peu d'aléatoire aux durées évite que beaucoup de clés expirent au même moment et sollicitent la base de données toutes ensemble.",
    ],
  ],
};
