import { defineTech, same } from "./types";

// Systems programming: C, C++, Unix system calls, threads, embedded.

export const c = defineTech(
  {
    id: "c",
    label: same("C"),
    family: "language",
    tool: true,
    exact: ["c"],
    aliases: [
      "langage c", "language c", "c language", "programmation en c", "programming in c", "developpement en c", "en c", "in c",
      "ansi c", "embedded c", "c89", "c99", "c11", "c17", "c/c++", "c / c++", "c et c++", "c and c++", "(c)",
    ],
  },
  [
    [
      "pointers", "concept",
      "What is a pointer in C, and what can you do with one that you could not do without?",
      "Qu'est-ce qu'un pointeur en C, et qu'est-ce qu'il permet de faire qu'on ne pourrait pas faire sans ?",
      "A pointer is a variable that holds the address of another value in memory. It lets a function modify the caller's variables, lets you work with arrays and strings without copying them, and it is the only way to use memory allocated at runtime with malloc. The price: you must make sure it always points to valid memory.",
      "Un pointeur est une variable qui contient l'adresse d'une autre valeur en mémoire. Il permet à une fonction de modifier les variables de l'appelant, de manipuler des tableaux et des chaînes sans les copier, et c'est le seul moyen d'utiliser la mémoire allouée à l'exécution avec malloc. En contrepartie, il faut s'assurer qu'il pointe toujours vers une zone valide.",
    ],
    [
      "stack-heap", "compare",
      "What is the difference between memory on the stack and memory on the heap in C? When do you need malloc?",
      "Quelle est la différence entre la mémoire sur la pile (stack) et sur le tas (heap) en C ? Quand a-t-on besoin de malloc ?",
      "The stack holds local variables: it is fast, managed automatically and freed when the function returns, but it is small. The heap is memory you request yourself with malloc and give back with free: you need it when the size is only known at runtime, or when the data must outlive the function that created it.",
      "La pile contient les variables locales : elle est rapide, gérée automatiquement et libérée au retour de la fonction, mais elle est petite. Le tas, c'est la mémoire qu'on demande soi-même avec malloc et qu'on rend avec free : on en a besoin quand la taille n'est connue qu'à l'exécution, ou quand les données doivent survivre à la fonction qui les a créées.",
    ],
    [
      "memory-leak", "troubleshoot",
      "Your C program uses more and more memory the longer it runs. How do you find and fix the leak?",
      "{Votre|Ton} programme C consomme de plus en plus de mémoire au fil du temps. Comment {trouvez-vous|trouves-tu} et {corrigez-vous|corriges-tu} la fuite ?",
      "I first reproduce it and run the program under Valgrind, or with AddressSanitizer's leak detector, which point to the allocation that is never freed. Then I check who owns that memory and add the missing free on every path, including the error paths. To prevent it, I keep one clear owner for each allocation.",
      "Je commence par reproduire le problème et lancer le programme sous Valgrind, ou avec le détecteur de fuites d'AddressSanitizer, qui indiquent l'allocation jamais libérée. Ensuite je vérifie qui est propriétaire de cette mémoire et j'ajoute le free manquant sur tous les chemins, y compris les chemins d'erreur. Pour l'éviter, je garde un seul propriétaire clair par allocation.",
    ],
    [
      "segfault", "troubleshoot",
      "Your program crashes with a segmentation fault. What are the usual causes, and how do you track it down?",
      "{Votre|Ton} programme plante avec une segmentation fault. Quelles en sont les causes habituelles, et comment {remontez-vous|remontes-tu} jusqu'à l'origine ?",
      "A segmentation fault means the program touched memory it may not access: dereferencing a NULL or uninitialised pointer, reading past the end of an array, using memory after free, or a stack overflow caused by deep recursion. I compile with -g and -fsanitize=address, or run the program in gdb to get the backtrace at the crash, then inspect the pointer involved.",
      "Une segmentation fault signifie que le programme a accédé à une mémoire interdite : déréférencement d'un pointeur NULL ou non initialisé, lecture après la fin d'un tableau, utilisation après un free, ou dépassement de pile dû à une récursion trop profonde. Je compile avec -g et -fsanitize=address, ou je lance gdb pour obtenir la pile d'appels au moment du crash, puis j'inspecte le pointeur en cause.",
    ],
    [
      "strings", "concept",
      "How are strings represented in C, and what can go wrong with the terminating null character?",
      "Comment une chaîne de caractères est-elle représentée en C, et qu'est-ce qui peut mal tourner avec le caractère nul de fin ?",
      "A string in C is just an array of char that ends with the null character, '\\0'. Functions like strlen or printf rely on that terminator: if it is missing, they read past the end of the buffer. That is why you allocate one extra byte for it, and why a function like strncpy, which may not add it, must be used with care.",
      "En C, une chaîne n'est qu'un tableau de char terminé par le caractère nul, '\\0'. Des fonctions comme strlen ou printf s'appuient sur ce terminateur : s'il manque, elles lisent au-delà du tampon. C'est pour ça qu'on alloue un octet de plus, et qu'une fonction comme strncpy, qui peut ne pas l'ajouter, s'utilise avec prudence.",
    ],
    [
      "const-pointers", "compare",
      "What is the difference between const int *p, int *const p and const int *const p?",
      "Quelle est la différence entre const int *p, int *const p et const int *const p ?",
      "const int *p is a pointer to a constant int: you cannot change the value through p, but p can point elsewhere. int *const p is a constant pointer: it always points to the same place, but the value can change. const int *const p combines both. Reading the declaration from right to left helps.",
      "const int *p est un pointeur vers un int constant : on ne peut pas modifier la valeur via p, mais p peut pointer ailleurs. int *const p est un pointeur constant : il pointe toujours au même endroit, mais la valeur peut changer. const int *const p combine les deux. Lire la déclaration de droite à gauche aide.",
    ],
    [
      "static", "concept",
      "What does the keyword static mean in C, inside a function and at file level?",
      "Que signifie le mot-clé static en C, dans une fonction et au niveau d'un fichier ?",
      "Inside a function, a static variable keeps its value between calls, because it lives for the whole program instead of on the stack. At file level, static limits the visibility of a global variable or a function to that file, which avoids name clashes and hides internal helpers.",
      "Dans une fonction, une variable static garde sa valeur d'un appel à l'autre, car elle existe pendant toute la durée du programme au lieu d'être sur la pile. Au niveau d'un fichier, static limite la visibilité d'une variable globale ou d'une fonction à ce fichier, ce qui évite les conflits de noms et cache les fonctions internes.",
    ],
    [
      "compilation", "concept",
      "What happens between your .c file and the executable? Walk me through preprocessing, compiling and linking.",
      "Que se passe-t-il entre {votre|ton} fichier .c et l'exécutable ? {Décrivez|Décris} le préprocesseur, la compilation et l'édition de liens.",
      "The preprocessor handles the # directives: it pastes the headers, expands the macros and removes what #ifdef excludes. The compiler then turns each .c file into an object file of machine code. Finally the linker joins the object files and the libraries and resolves the calls between them to produce the executable. An \"undefined reference\" error comes from that last step.",
      "Le préprocesseur traite les directives # : il insère les en-têtes, développe les macros et retire ce que #ifdef exclut. Le compilateur transforme ensuite chaque fichier .c en fichier objet, en code machine. Enfin, l'éditeur de liens assemble les fichiers objets et les bibliothèques et résout les appels entre eux pour produire l'exécutable. Une erreur « undefined reference » vient de cette dernière étape.",
    ],
    [
      "buffer-overflow", "best_practice",
      "What is a buffer overflow, and which habits help you avoid it in C?",
      "Qu'est-ce qu'un dépassement de tampon (buffer overflow), et quelles habitudes {vous aident|t'aident} à l'éviter en C ?",
      "A buffer overflow is writing past the end of an array: it corrupts the memory next to it, can crash the program, and can be exploited by an attacker. I always keep track of buffer sizes, use bounded functions like snprintf, never use gets, check the length of every input, and test with AddressSanitizer or Valgrind.",
      "Un dépassement de tampon, c'est écrire au-delà de la fin d'un tableau : ça corrompt la mémoire voisine, ça peut faire planter le programme et être exploité par un attaquant. Je garde toujours la taille des tampons, j'utilise des fonctions bornées comme snprintf, jamais gets, je vérifie la longueur de chaque entrée, et je teste avec AddressSanitizer ou Valgrind.",
    ],
    [
      "makefile", "practice",
      "What does a Makefile do for a C project, and how does it avoid recompiling everything?",
      "À quoi sert un Makefile dans un projet C, et comment évite-t-il de tout recompiler ?",
      "A Makefile describes how to build the project: targets, the files they depend on, and the commands that produce them. make compares modification dates, so it only recompiles the object files whose sources or headers changed, then links again. A typical Makefile has the rules all, clean, fclean and re, and compiles with flags like -Wall -Wextra -Werror.",
      "Un Makefile décrit comment construire le projet : des cibles, les fichiers dont elles dépendent, et les commandes qui les produisent. make compare les dates de modification : il ne recompile que les fichiers objets dont les sources ou les en-têtes ont changé, puis refait l'édition de liens. Un Makefile classique a les règles all, clean, fclean et re, et compile avec des options comme -Wall -Wextra -Werror.",
    ],
    [
      "struct-padding", "concept",
      "Why can the sizeof of a struct be larger than the sum of its fields?",
      "Pourquoi le sizeof d'une structure peut-il être plus grand que la somme de ses champs ?",
      "Because of alignment: the processor reads a value faster when it starts at an address that is a multiple of its size, so the compiler adds padding bytes between the fields and at the end. Ordering the fields from the largest to the smallest usually reduces the padding.",
      "À cause de l'alignement : le processeur lit plus vite une valeur qui commence à une adresse multiple de sa taille, donc le compilateur ajoute des octets de remplissage entre les champs et à la fin. Ranger les champs du plus grand au plus petit réduit généralement ce remplissage.",
    ],
    [
      "function-pointers", "practice",
      "What is a function pointer in C? Give me a case where it is useful.",
      "Qu'est-ce qu'un pointeur de fonction en C ? {Donnez-moi|Donne-moi} un cas où c'est utile.",
      "A function pointer stores the address of a function, so the program can choose at runtime which function to call. The classic case is qsort, which takes a comparison function. You can also map a command or a format specifier to the function that handles it, instead of a long chain of if statements.",
      "Un pointeur de fonction contient l'adresse d'une fonction, ce qui permet de choisir à l'exécution quelle fonction appeler. Le cas classique, c'est qsort, qui reçoit une fonction de comparaison. On peut aussi associer une commande ou un spécificateur de format à la fonction qui le traite, au lieu d'une longue suite de if.",
    ],
    [
      "variadic", "concept",
      "How does a variadic function like printf read its arguments, and what are the risks?",
      "Comment une fonction variadique comme printf lit-elle ses arguments, et quels sont les risques ?",
      "It uses the macros of stdarg.h: va_start, then va_arg to read each argument with the type it expects, then va_end. The function cannot know how many arguments it received or their types, so printf deduces them from the format string. If the format and the arguments do not match, the behaviour is undefined, and a format controlled by a user becomes a security hole.",
      "Elle utilise les macros de stdarg.h : va_start, puis va_arg pour lire chaque argument avec le type attendu, puis va_end. La fonction ne peut pas connaître le nombre ni le type des arguments reçus, donc printf les déduit de la chaîne de format. Si le format et les arguments ne correspondent pas, le comportement est indéfini, et un format contrôlé par l'utilisateur devient une faille de sécurité.",
    ],
    [
      "undefined-behaviour", "concept",
      "What is undefined behaviour in C? Give two examples.",
      "Qu'est-ce qu'un comportement indéfini (undefined behaviour) en C ? {Donnez|Donne} deux exemples.",
      "It is code the C standard gives no meaning to, so the compiler may do anything: it can seem to work, crash, or break only once optimisations are on. Examples: reading an uninitialised variable, overflowing a signed int, dereferencing NULL, accessing an array out of bounds, or modifying a variable twice in one expression, like i = i++.",
      "C'est du code auquel la norme C ne donne aucun sens, donc le compilateur peut faire n'importe quoi : ça peut sembler marcher, planter, ou casser seulement avec les optimisations. Exemples : lire une variable non initialisée, faire déborder un int signé, déréférencer NULL, sortir des bornes d'un tableau, ou modifier deux fois une variable dans la même expression, comme i = i++.",
    ],
    [
      "debug-tools", "practice",
      "Which tools do you use to debug a C program, and what does each one tell you? gdb, Valgrind, sanitizers…",
      "Quels outils {utilisez-vous|utilises-tu} pour déboguer un programme C, et qu'est-ce que chacun {vous |t'}apprend ? gdb, Valgrind, sanitizers…",
      "gdb lets me stop the program, step through it, print variables and get the backtrace of a crash. Valgrind reports invalid reads and writes, and memory leaks. The sanitizers, like -fsanitize=address or undefined, catch the same kind of errors at the moment they happen, with a precise report. And compiler warnings, with -Wall -Wextra, catch many bugs before anything runs.",
      "gdb permet d'arrêter le programme, d'avancer pas à pas, d'afficher les variables et d'obtenir la pile d'appels d'un crash. Valgrind signale les lectures et écritures invalides, et les fuites mémoire. Les sanitizers, comme -fsanitize=address ou undefined, attrapent ce type d'erreurs au moment où elles se produisent, avec un rapport précis. Et les avertissements du compilateur, avec -Wall -Wextra, évitent beaucoup de bugs avant même l'exécution.",
    ],
  ],
);

export const cpp = defineTech(
  {
    id: "cpp",
    label: same("C++"),
    family: "language",
    tool: true,
    aliases: ["c++", "cpp", "c++11", "c++14", "c++17", "c++20", "c++23", "modern c++", "cplusplus"],
  },
  [
    [
      "raii", "concept",
      "What is RAII in C++, and why does it matter?",
      "Qu'est-ce que le RAII en C++, et pourquoi est-ce important ?",
      "RAII means Resource Acquisition Is Initialisation: a resource is tied to the lifetime of an object. The constructor acquires it and the destructor releases it, so it is freed automatically when the object goes out of scope, even when an exception is thrown. std::unique_ptr, std::lock_guard and std::fstream all work this way.",
      "RAII veut dire Resource Acquisition Is Initialization : une ressource est liée à la durée de vie d'un objet. Le constructeur l'acquiert et le destructeur la libère, donc elle est rendue automatiquement quand l'objet sort de sa portée, même si une exception est levée. std::unique_ptr, std::lock_guard et std::fstream fonctionnent tous ainsi.",
    ],
    [
      "smart-pointers", "compare",
      "What are unique_ptr and shared_ptr, and when would you choose one over the other?",
      "Que sont unique_ptr et shared_ptr, et quand choisir l'un plutôt que l'autre ?",
      "A unique_ptr has a single owner: it cannot be copied, only moved, and it deletes the object when it goes away. A shared_ptr counts its owners and deletes the object when the last one disappears. I use unique_ptr by default, because it is simpler and costs nothing, and shared_ptr only when ownership is really shared, with weak_ptr to break cycles.",
      "Un unique_ptr a un seul propriétaire : on ne peut pas le copier, seulement le déplacer, et il détruit l'objet quand il disparaît. Un shared_ptr compte ses propriétaires et détruit l'objet quand le dernier disparaît. J'utilise unique_ptr par défaut, car il est plus simple et ne coûte rien, et shared_ptr seulement quand la propriété est vraiment partagée, avec weak_ptr pour casser les cycles.",
    ],
    [
      "references", "compare",
      "What is the difference between a pointer and a reference in C++?",
      "Quelle est la différence entre un pointeur et une référence en C++ ?",
      "A reference is an alias for an existing object: it must be initialised, cannot be null and cannot be bound to another object later. A pointer is a variable that holds an address: it can be null, change target, and must be dereferenced explicitly. I use references for parameters by default, and pointers when \"no object\" is a valid case or the target must change.",
      "Une référence est un alias d'un objet existant : elle doit être initialisée, ne peut pas être nulle et ne peut pas désigner un autre objet ensuite. Un pointeur est une variable qui contient une adresse : il peut être nul, changer de cible, et il faut le déréférencer explicitement. J'utilise des références pour les paramètres par défaut, et des pointeurs quand « pas d'objet » est un cas valide ou que la cible doit changer.",
    ],
    [
      "canonical-form", "concept",
      "What is the rule of three, or the Orthodox Canonical Form, and what goes wrong if you ignore it?",
      "Qu'est-ce que la règle des trois, ou forme canonique de Coplien, et que se passe-t-il si on l'ignore ?",
      "A class that manages a resource needs a destructor, a copy constructor and a copy assignment operator that agree with each other; the Orthodox Canonical Form adds a default constructor. If you only write the destructor, the default copy duplicates the raw pointer: two objects free the same memory, which gives a double free. In modern C++, the rule of five adds the two move operations.",
      "Une classe qui gère une ressource a besoin d'un destructeur, d'un constructeur de copie et d'un opérateur d'affectation cohérents entre eux ; la forme canonique de Coplien ajoute un constructeur par défaut. Si on n'écrit que le destructeur, la copie par défaut recopie le pointeur brut : deux objets libèrent la même mémoire, ce qui donne un double free. En C++ moderne, la règle des cinq ajoute les deux opérations de déplacement.",
    ],
    [
      "virtual", "concept",
      "How do virtual functions work, and why does a base class usually need a virtual destructor?",
      "Comment fonctionnent les fonctions virtuelles, et pourquoi une classe de base a-t-elle généralement besoin d'un destructeur virtuel ?",
      "A virtual function is resolved at runtime: each polymorphic class has a table of function pointers, the vtable, and every object points to the table of its class. So a call through a base pointer runs the derived version. Without a virtual destructor, deleting a derived object through a base pointer only runs the base destructor, which leaks or corrupts resources.",
      "Une fonction virtuelle est résolue à l'exécution : chaque classe polymorphe a une table de pointeurs de fonctions, la vtable, et chaque objet pointe vers celle de sa classe. Un appel via un pointeur de base exécute donc la version dérivée. Sans destructeur virtuel, détruire un objet dérivé via un pointeur de base n'appelle que le destructeur de base, ce qui fait fuir ou corrompt des ressources.",
    ],
    [
      "abstract", "design",
      "When would you use an abstract class or a pure interface in C++? Give an example from a project.",
      "Quand {utiliseriez-vous|utiliserais-tu} une classe abstraite ou une interface pure en C++ ? {Donnez|Donne} un exemple tiré d'un projet.",
      "When several types share a behaviour that callers should use without knowing the concrete type: for example an Animal class with a pure virtual makeSound, or a Shape with a pure virtual area. The abstract class defines the contract, the derived classes implement it, and the rest of the code depends only on the interface, so adding a new type does not change it.",
      "Quand plusieurs types partagent un comportement que l'appelant doit utiliser sans connaître le type concret : par exemple une classe Animal avec une méthode virtuelle pure makeSound, ou une Shape avec une méthode virtuelle pure area. La classe abstraite définit le contrat, les classes dérivées l'implémentent, et le reste du code ne dépend que de l'interface : ajouter un nouveau type ne le change pas.",
    ],
    [
      "templates", "concept",
      "What are templates for in C++, and what do they cost?",
      "À quoi servent les templates en C++, et quel est leur coût ?",
      "Templates let you write a function or a class once for any type, like std::vector<T> or a max function, with the types checked at compile time and no runtime cost. The costs: longer compile times, code generated again for each type used, harder error messages, and implementations that usually have to live in the headers.",
      "Les templates permettent d'écrire une fonction ou une classe une seule fois pour n'importe quel type, comme std::vector<T> ou une fonction max, avec une vérification des types à la compilation et sans coût à l'exécution. En contrepartie : une compilation plus longue, du code généré à nouveau pour chaque type utilisé, des messages d'erreur plus difficiles, et des implémentations qui doivent en général rester dans les en-têtes.",
    ],
    [
      "containers", "compare",
      "std::vector, std::list, std::map: how do you choose a container?",
      "std::vector, std::list, std::map : comment choisir un conteneur ?",
      "std::vector is the default: contiguous memory, fast access by index and fast iteration, cheap insertion at the end. std::list makes insertion and removal in the middle cheap once you hold an iterator, but has no index access and uses the cache badly. std::map keeps its keys sorted with lookups in O(log n); std::unordered_map gives constant-time lookups on average when the order does not matter.",
      "std::vector est le choix par défaut : mémoire contiguë, accès rapide par indice et parcours rapide, ajout en fin peu coûteux. std::list rend l'insertion et la suppression au milieu peu coûteuses quand on tient un itérateur, mais sans accès par indice et avec un mauvais usage du cache. std::map garde ses clés triées avec des recherches en O(log n) ; std::unordered_map offre des recherches en temps constant en moyenne quand l'ordre n'importe pas.",
    ],
    [
      "iterator-invalidation", "troubleshoot",
      "You erase elements from a std::vector inside a loop and the program misbehaves. What is going on?",
      "{Vous supprimez|Tu supprimes} des éléments d'un std::vector dans une boucle, et le programme se comporte bizarrement. Que se passe-t-il ?",
      "erase invalidates the iterator of the erased element and every iterator after it, so incrementing it afterwards is undefined behaviour. The fix is to use the iterator that erase returns, it = v.erase(it), and only increment when nothing was erased, or to use the erase-remove idiom with std::remove_if.",
      "erase invalide l'itérateur de l'élément supprimé et tous ceux qui suivent, donc l'incrémenter ensuite est un comportement indéfini. La correction consiste à utiliser l'itérateur que renvoie erase, it = v.erase(it), et à n'incrémenter que si rien n'a été supprimé, ou à utiliser l'idiome erase-remove avec std::remove_if.",
    ],
    [
      "exceptions", "best_practice",
      "How do exceptions work in C++, and what does exception safety mean for your code?",
      "Comment fonctionnent les exceptions en C++, et que signifie la sûreté face aux exceptions (exception safety) pour {votre|ton} code ?",
      "throw creates an exception object, then the stack is unwound and the destructors of local objects run until a matching catch is found. Exception safety means that when an exception happens, nothing leaks and objects stay in a valid state. RAII makes this easy; I also catch exceptions by reference and never let one escape a destructor.",
      "throw crée un objet exception, puis la pile est déroulée et les destructeurs des objets locaux s'exécutent jusqu'à un catch correspondant. La sûreté face aux exceptions, c'est garantir qu'en cas d'exception rien ne fuit et que les objets restent dans un état valide. Le RAII rend ça simple ; j'attrape aussi les exceptions par référence et je n'en laisse jamais sortir d'un destructeur.",
    ],
    [
      "casts", "compare",
      "static_cast, dynamic_cast, const_cast, reinterpret_cast: what is each one for?",
      "static_cast, dynamic_cast, const_cast, reinterpret_cast : à quoi sert chacun ?",
      "static_cast does conversions checked at compile time, like int to double or a derived pointer to its base. dynamic_cast checks a downcast at runtime on polymorphic types: it returns nullptr, or throws for a reference, when the object is not of that type. const_cast adds or removes const. reinterpret_cast reinterprets the bits, for example a pointer as an integer: it is the most dangerous, for low-level code only.",
      "static_cast fait des conversions vérifiées à la compilation, comme int vers double ou un pointeur dérivé vers sa base. dynamic_cast vérifie à l'exécution une conversion vers une classe dérivée, sur des types polymorphes : il renvoie nullptr, ou lève une exception pour une référence, si l'objet n'est pas de ce type. const_cast ajoute ou retire const. reinterpret_cast réinterprète les bits, par exemple un pointeur en entier : c'est le plus dangereux, réservé au code bas niveau.",
    ],
    [
      "const-correctness", "best_practice",
      "What does a const member function guarantee, and why is const-correctness worth the effort?",
      "Que garantit une fonction membre const, et pourquoi la const-correctness vaut-elle l'effort ?",
      "A const member function promises not to change the observable state of the object, and it is the only kind of member function you can call on a const object or through a const reference. Being const-correct documents the intent, lets the compiler catch accidental changes, and lets you pass objects by const reference everywhere.",
      "Une fonction membre const promet de ne pas modifier l'état observable de l'objet, et c'est la seule qu'on peut appeler sur un objet const ou via une référence const. Être const-correct documente l'intention, laisse le compilateur repérer les modifications accidentelles, et permet de passer les objets par référence const partout.",
    ],
    [
      "operator-overloading", "practice",
      "When does it make sense to overload an operator? How would you write operator<< for your own class?",
      "Quand est-il pertinent de surcharger un opérateur ? Comment {écririez-vous|écrirais-tu} operator<< pour {votre|ta} propre classe ?",
      "When the operator has an obvious meaning for the type, like + for a fixed-point number or == to compare values, and behaves as it does for built-in types. operator<< is a free function that takes an std::ostream& and a const reference to my object: it writes the fields into the stream and returns the stream, so calls can be chained.",
      "Quand l'opérateur a un sens évident pour le type, comme + pour un nombre à virgule fixe ou == pour comparer des valeurs, et qu'il se comporte comme pour les types natifs. operator<< est une fonction libre qui prend un std::ostream& et une référence const vers mon objet : elle écrit les champs dans le flux et renvoie le flux, pour pouvoir enchaîner les appels.",
    ],
    [
      "move", "concept",
      "What does move semantics bring compared with copying? What does std::move actually do?",
      "Qu'apporte la sémantique de déplacement par rapport à la copie ? Que fait réellement std::move ?",
      "Moving transfers the resources of an object that is about to disappear instead of copying them: for example taking over a vector's buffer instead of copying every element, which is much cheaper. std::move itself moves nothing: it is only a cast to an rvalue reference, which allows the move constructor or the move assignment to be chosen.",
      "Le déplacement transfère les ressources d'un objet qui va disparaître au lieu de les copier : par exemple récupérer le tampon d'un vector au lieu de copier chaque élément, ce qui coûte beaucoup moins. std::move ne déplace rien lui-même : c'est un simple cast en référence rvalue, qui permet de choisir le constructeur ou l'affectation par déplacement.",
    ],
    [
      "new-malloc", "compare",
      "What is the difference between new and delete, and malloc and free, in C++?",
      "Quelle est la différence entre new et delete, et malloc et free, en C++ ?",
      "new allocates memory and calls the constructor; delete calls the destructor and frees the memory. They are typed, and new throws std::bad_alloc on failure. malloc and free only handle raw bytes: no constructor, no destructor, and malloc returns NULL on failure. You must never mix them, and in modern C++ smart pointers and containers avoid calling either one directly.",
      "new alloue la mémoire et appelle le constructeur ; delete appelle le destructeur et libère la mémoire. Ils sont typés, et new lève std::bad_alloc en cas d'échec. malloc et free ne gèrent que des octets bruts : ni constructeur ni destructeur, et malloc renvoie NULL en cas d'échec. Il ne faut jamais les mélanger, et en C++ moderne les pointeurs intelligents et les conteneurs évitent d'appeler l'un ou l'autre directement.",
    ],
  ],
);

export const posix = defineTech(
  {
    id: "posix",
    label: { en: "Unix system programming", fr: "Programmation système Unix" },
    family: "systems",
    tool: false,
    aliases: [
      "unix", "posix", "system programming", "systems programming", "programmation systeme", "developpement systeme",
      "appels systeme", "system calls", "syscalls", "fork", "execve", "ipc", "file descriptors", "unix processes",
    ],
  },
  [
    [
      "fork-exec", "concept",
      "What do fork, exec and wait do, and how do they work together to run a command?",
      "Que font fork, exec et wait, et comment s'articulent-ils pour lancer une commande ?",
      "fork creates a copy of the current process: it returns 0 in the child and the child's PID in the parent. In the child, exec replaces the program with the command to run, keeping the same PID and the open file descriptors. The parent calls wait or waitpid to wait for the child to finish and read its exit status. A shell runs every command this way.",
      "fork crée une copie du processus courant : il renvoie 0 dans l'enfant et le PID de l'enfant dans le parent. Dans l'enfant, exec remplace le programme par la commande à lancer, en gardant le même PID et les descripteurs ouverts. Le parent appelle wait ou waitpid pour attendre la fin de l'enfant et lire son code de sortie. Un shell lance chaque commande de cette façon.",
    ],
    [
      "pipes", "practice",
      "How would you connect two processes with a pipe, like ls | wc -l? Which system calls do you need?",
      "Comment {relieriez-vous|relierais-tu} deux processus par un pipe, comme ls | wc -l ? De quels appels système a-t-on besoin ?",
      "I call pipe to get two file descriptors, a read end and a write end, then fork twice. In the first child, dup2 puts the write end on standard output before the exec of ls; in the second, dup2 puts the read end on standard input before the exec of wc. Every process closes the ends it does not use, and the parent closes both and waits for the two children.",
      "J'appelle pipe pour obtenir deux descripteurs, une extrémité de lecture et une d'écriture, puis je fais deux fork. Dans le premier enfant, dup2 place l'extrémité d'écriture sur la sortie standard avant l'exec de ls ; dans le second, dup2 place l'extrémité de lecture sur l'entrée standard avant l'exec de wc. Chaque processus ferme les extrémités qu'il n'utilise pas, et le parent ferme les deux puis attend les deux enfants.",
    ],
    [
      "file-descriptors", "concept",
      "What is a file descriptor, and what do dup2 and close do with it?",
      "Qu'est-ce qu'un descripteur de fichier, et que font dup2 et close ?",
      "A file descriptor is a small integer that indexes the process's table of open files, pipes and sockets: 0, 1 and 2 are standard input, output and error. dup2(old, new) makes new refer to the same open file as old, which is how redirections work. close releases the descriptor; forgetting it leaks descriptors and can keep pipes open.",
      "Un descripteur de fichier est un petit entier qui indexe la table des fichiers, pipes et sockets ouverts du processus : 0, 1 et 2 sont l'entrée standard, la sortie et l'erreur. dup2(ancien, nouveau) fait désigner à nouveau le même fichier ouvert que ancien : c'est ainsi que fonctionnent les redirections. close libère le descripteur ; l'oublier crée des fuites et peut laisser des pipes ouverts.",
    ],
    [
      "zombies", "troubleshoot",
      "Your program leaves zombie processes behind. What is a zombie, and how do you fix it?",
      "{Votre|Ton} programme laisse des processus zombies derrière lui. Qu'est-ce qu'un zombie, et comment corriger ça ?",
      "A zombie is a child that has finished but whose parent has not read its exit status yet, so it keeps an entry in the process table. The fix: the parent calls wait or waitpid for every child, or handles SIGCHLD and collects its children there. If the parent dies, init adopts the zombies and cleans them up.",
      "Un zombie est un enfant terminé dont le parent n'a pas encore lu le code de sortie : il garde une entrée dans la table des processus. Pour corriger, le parent appelle wait ou waitpid pour chaque enfant, ou gère SIGCHLD et les récupère à ce moment-là. Si le parent meurt, init adopte les zombies et les nettoie.",
    ],
    [
      "signals", "concept",
      "What is a signal in Unix? How would you handle Ctrl-C in a program such as a shell?",
      "Qu'est-ce qu'un signal sous Unix ? Comment {géreriez-vous|gérerais-tu} Ctrl-C dans un programme comme un shell ?",
      "A signal is an asynchronous notification sent to a process: SIGINT for Ctrl-C, SIGTERM to ask it to stop, SIGSEGV after an invalid memory access. A shell installs a handler with sigaction: on Ctrl-C it shows a new prompt instead of quitting, while the child running a command keeps the default behaviour and stops. The handler must stay minimal and only call async-signal-safe functions.",
      "Un signal est une notification asynchrone envoyée à un processus : SIGINT pour Ctrl-C, SIGTERM pour lui demander de s'arrêter, SIGSEGV après un accès mémoire invalide. Un shell installe un gestionnaire avec sigaction : sur Ctrl-C, il affiche un nouveau prompt au lieu de quitter, tandis que l'enfant qui exécute une commande garde le comportement par défaut et s'arrête. Le gestionnaire doit rester minimal et n'appeler que des fonctions async-signal-safe.",
    ],
    [
      "pipe-hangs", "troubleshoot",
      "Two processes are connected by a pipe, but the reader never finishes. What has probably been forgotten?",
      "Deux processus sont reliés par un pipe, mais celui qui lit ne se termine jamais. Qu'a-t-on probablement oublié ?",
      "Probably to close a write end. The reader only gets end-of-file once every write end of the pipe is closed, in every process. If the parent, or the reader itself, still holds a copy of the write end, the reader waits forever.",
      "Probablement de fermer une extrémité d'écriture. Le lecteur ne reçoit la fin de fichier qu'une fois toutes les extrémités d'écriture du pipe fermées, dans tous les processus. Si le parent, ou le lecteur lui-même, garde une copie de l'extrémité d'écriture, le lecteur attend indéfiniment.",
    ],
    [
      "environment", "concept",
      "How does a program receive its environment variables, and how does a shell use PATH to find the program to run?",
      "Comment un programme reçoit-il ses variables d'environnement, et comment un shell utilise-t-il le PATH pour trouver le programme à lancer ?",
      "The environment is a list of KEY=value strings that the parent passes to execve and that children inherit; in C it is the third parameter of main or the environ variable, read with getenv. For a command without a slash, the shell splits PATH on the colons and tries each directory in order until it finds an executable file with that name.",
      "L'environnement est une liste de chaînes CLÉ=valeur que le parent transmet à execve et dont les enfants héritent ; en C, c'est le troisième paramètre de main ou la variable environ, qu'on lit avec getenv. Pour une commande sans slash, le shell découpe le PATH sur les deux-points et essaie chaque dossier dans l'ordre jusqu'à trouver un fichier exécutable de ce nom.",
    ],
    [
      "syscall-vs-libc", "compare",
      "What is the difference between a system call and a library function, for example write and printf?",
      "Quelle est la différence entre un appel système et une fonction de bibliothèque, par exemple write et printf ?",
      "A system call asks the kernel to do something for the process, like write, which sends bytes to a file descriptor; it switches to kernel mode, which is relatively costly. printf is a function of the C library that runs in user space: it formats the text, keeps it in a buffer and calls write only when needed. That is why printf output can appear late, or in a surprising order next to write.",
      "Un appel système demande au noyau de faire quelque chose pour le processus, comme write, qui envoie des octets vers un descripteur ; il passe en mode noyau, ce qui coûte relativement cher. printf est une fonction de la bibliothèque C qui tourne en espace utilisateur : elle formate le texte, le garde dans un tampon et n'appelle write que lorsque c'est nécessaire. C'est pour ça qu'une sortie de printf peut apparaître en retard, ou dans un ordre surprenant à côté de write.",
    ],
  ],
);

export const concurrency = defineTech(
  {
    id: "concurrency",
    label: { en: "Concurrency (threads)", fr: "Concurrence (threads)" },
    family: "systems",
    tool: false,
    aliases: [
      "multithreading", "multi-threading", "multi threading", "multithread", "multithreaded", "threads", "threading", "pthread", "pthreads",
      "concurrency", "concurrent programming", "programmation concurrente", "programmation parallele", "parallel programming",
      "mutex", "mutexes", "semaphore", "semaphores", "race condition", "race conditions", "deadlock",
    ],
  },
  [
    [
      "thread-vs-process", "compare",
      "What is the difference between a process and a thread?",
      "Quelle est la différence entre un processus et un thread ?",
      "A process has its own memory space and resources; processes are isolated and communicate through pipes, sockets or shared memory. Threads live inside one process and share its memory, which makes communication easy and creation cheaper, but every shared access must be synchronised, and a crash in one thread brings down the whole process.",
      "Un processus a son propre espace mémoire et ses propres ressources ; les processus sont isolés et communiquent par des pipes, des sockets ou de la mémoire partagée. Les threads vivent dans un même processus et partagent sa mémoire, ce qui facilite la communication et coûte moins cher à créer, mais chaque accès partagé doit être synchronisé, et un crash dans un thread fait tomber tout le processus.",
    ],
    [
      "race-condition", "concept",
      "What is a race condition? Give an example and the way to prevent it.",
      "Qu'est-ce qu'une race condition (situation de compétition) ? {Donnez|Donne} un exemple et la façon de l'éviter.",
      "It is when the result depends on the order in which threads run. For example, two threads run counter++ at the same time: each one reads, adds one and writes back, so one increment can be lost. You prevent it by protecting the shared data with a mutex, by using atomic operations, or by not sharing the data at all.",
      "C'est quand le résultat dépend de l'ordre d'exécution des threads. Par exemple, deux threads exécutent counter++ en même temps : chacun lit, ajoute un et réécrit, donc un incrément peut être perdu. On l'évite en protégeant la donnée partagée par un mutex, en utilisant des opérations atomiques, ou en ne partageant pas la donnée.",
    ],
    [
      "mutex", "concept",
      "What is a mutex for, and what happens if you forget to unlock it?",
      "À quoi sert un mutex, et que se passe-t-il si on oublie de le déverrouiller ?",
      "A mutex ensures that only one thread at a time runs a critical section: a thread locks it before touching the shared data and unlocks it afterwards. If you forget to unlock it, for example on an early return or an error path, every other thread that tries to lock it stays blocked forever. In C++, std::lock_guard unlocks it automatically.",
      "Un mutex garantit qu'un seul thread à la fois exécute une section critique : un thread le verrouille avant de toucher aux données partagées et le déverrouille après. Si on oublie de le déverrouiller, par exemple sur un return anticipé ou un chemin d'erreur, tous les autres threads qui veulent le verrouiller restent bloqués pour toujours. En C++, std::lock_guard le déverrouille automatiquement.",
    ],
    [
      "deadlock", "troubleshoot",
      "Your multithreaded program freezes from time to time. How do you check whether it is a deadlock, and how do you avoid one?",
      "{Votre|Ton} programme multithread se fige de temps en temps. Comment {vérifiez-vous|vérifies-tu} s'il s'agit d'un interblocage (deadlock), et comment l'éviter ?",
      "I attach a debugger such as gdb to the frozen process and look at the backtrace of every thread: if two threads each wait for a lock held by the other, it is a deadlock. To avoid it, I always take locks in the same global order, hold them as briefly as possible, avoid calling unknown code while holding a lock, and sometimes use a try-lock with a timeout.",
      "J'attache un débogueur comme gdb au processus figé et je regarde la pile d'appels de chaque thread : si deux threads attendent chacun un verrou détenu par l'autre, c'est un interblocage. Pour l'éviter, je prends toujours les verrous dans le même ordre global, je les garde le moins longtemps possible, j'évite d'appeler du code inconnu en tenant un verrou, et j'utilise parfois un try-lock avec un délai.",
    ],
    [
      "philosophers", "design",
      "Explain the dining philosophers problem and one way to solve it without deadlock or starvation.",
      "{Expliquez|Explique} le problème des philosophes et une façon de le résoudre sans interblocage ni famine.",
      "Philosophers sit around a table with one fork between each pair of neighbours, and each needs both nearby forks to eat. If they all take their left fork at the same time, nobody can take the right one: deadlock. A simple fix breaks the symmetry, for example odd philosophers take the left fork first and even ones the right. Against starvation, a monitor checks how long each philosopher has gone without eating.",
      "Des philosophes sont assis autour d'une table, avec une fourchette entre chaque paire de voisins, et chacun a besoin des deux fourchettes voisines pour manger. Si tous prennent leur fourchette de gauche en même temps, personne ne peut prendre celle de droite : interblocage. Une solution simple casse la symétrie, par exemple les philosophes impairs prennent d'abord la fourchette de gauche et les pairs celle de droite. Contre la famine, un moniteur surveille le temps écoulé depuis le dernier repas de chacun.",
    ],
    [
      "mutex-vs-semaphore", "compare",
      "What is the difference between a mutex and a semaphore?",
      "Quelle est la différence entre un mutex et un sémaphore ?",
      "A mutex is a lock with an owner: the thread that locks it must unlock it, and it lets one thread at a time into a critical section. A semaphore is a counter: wait decrements it and blocks at zero, post increments it, and any thread or process can post. It limits access to N resources, or signals events between threads or processes.",
      "Un mutex est un verrou avec un propriétaire : le thread qui le verrouille doit le déverrouiller, et il laisse entrer un seul thread à la fois dans une section critique. Un sémaphore est un compteur : wait le décrémente et bloque à zéro, post l'incrémente, et n'importe quel thread ou processus peut faire post. Il sert à limiter l'accès à N ressources, ou à signaler des événements entre threads ou processus.",
    ],
    [
      "heisenbug", "practice",
      "How would you track down a bug that only shows up from time to time in multithreaded code?",
      "Comment {traqueriez-vous|traquerais-tu} un bug qui n'apparaît que de temps en temps dans du code multithread ?",
      "First I try to make it reproducible: run the program many times, add load, or change the timing. Then I use the thread sanitizer, -fsanitize=thread, or Helgrind, which detect data races even when the bug does not show. Logs with the thread id and a timestamp help, but printing changes the timing and can hide the bug, so I also review every piece of shared data and how it is protected.",
      "D'abord, j'essaie de le rendre reproductible : lancer le programme de nombreuses fois, ajouter de la charge, ou modifier le timing. Ensuite j'utilise le thread sanitizer, -fsanitize=thread, ou Helgrind, qui détectent les accès concurrents même quand le bug ne se manifeste pas. Des logs avec l'identifiant du thread et l'heure aident, mais les affichages modifient le timing et peuvent masquer le bug, donc je relis aussi chaque donnée partagée et la façon dont elle est protégée.",
    ],
  ],
);

export const embedded = defineTech(
  {
    id: "embedded",
    label: { en: "Embedded systems", fr: "Systèmes embarqués" },
    family: "systems",
    tool: false,
    aliases: [
      "embedded", "embedded systems", "embedded c", "embarque", "systemes embarques", "logiciel embarque", "microcontroller", "microcontrollers",
      "microcontroleur", "microcontroleurs", "mcu", "arduino", "stm32", "esp32", "rtos", "freertos", "zephyr", "firmware", "bare metal", "bare-metal",
      "iot", "raspberry pi", "arm cortex",
    ],
  },
  [
    [
      "volatile", "concept",
      "What does volatile mean in C, and why does it matter in embedded code?",
      "Que signifie volatile en C, et pourquoi est-ce important en embarqué ?",
      "volatile tells the compiler that a variable can change outside the normal flow of the program, so it must read it from memory every time instead of keeping it in a register or optimising the access away. It is needed for hardware registers and for variables shared with an interrupt handler. It does not make an access atomic or thread-safe.",
      "volatile indique au compilateur qu'une variable peut changer en dehors du déroulement normal du programme : il doit donc la relire en mémoire à chaque fois, au lieu de la garder dans un registre ou de supprimer l'accès par optimisation. C'est nécessaire pour les registres matériels et les variables partagées avec une routine d'interruption. Ça ne rend pas l'accès atomique ni sûr entre threads.",
    ],
    [
      "interrupts", "best_practice",
      "What is an interrupt, and what should you avoid doing inside an interrupt handler?",
      "Qu'est-ce qu'une interruption, et que faut-il éviter de faire dans une routine d'interruption ?",
      "An interrupt is a hardware signal that pauses the main code to run a handler right away, for example when a byte arrives on a serial port or a timer expires. The handler must be short: no long loops, no blocking waits, no heavy printing and no dynamic allocation. Usually it reads the data, sets a flag or fills a buffer, and the main loop does the real work.",
      "Une interruption est un signal matériel qui suspend le code principal pour exécuter tout de suite une routine, par exemple quand un octet arrive sur un port série ou qu'un timer expire. La routine doit être courte : pas de longues boucles, pas d'attente bloquante, pas d'affichage lourd ni d'allocation dynamique. En général, elle lit la donnée, lève un drapeau ou remplit un tampon, et la boucle principale fait le vrai travail.",
    ],
    [
      "bits", "practice",
      "How do you set, clear and test a single bit of a hardware register in C?",
      "Comment mettre à 1, mettre à 0 et tester un bit précis d'un registre matériel en C ?",
      "With bitwise operators and a mask: reg |= (1u << n) sets bit n, reg &= ~(1u << n) clears it, and (reg & (1u << n)) != 0 tests it. The register is declared volatile, and if an interrupt can modify the same register, the read-modify-write sequence must be protected.",
      "Avec les opérateurs bit à bit et un masque : reg |= (1u << n) met le bit n à 1, reg &= ~(1u << n) le met à 0, et (reg & (1u << n)) != 0 le teste. Le registre est déclaré volatile, et si une interruption peut modifier le même registre, la séquence lecture-modification-écriture doit être protégée.",
    ],
    [
      "constraints", "concept",
      "What changes when you write code for a microcontroller with only a few kilobytes of RAM?",
      "Qu'est-ce qui change quand on écrit du code pour un microcontrôleur qui n'a que quelques kilo-octets de RAM ?",
      "Every byte counts: little or no dynamic allocation, so memory is planned up front, often with static buffers. You watch the stack size, choose small integer types, avoid heavy libraries and floating point when the chip has no FPU, and measure the code size. Power consumption and timing constraints matter too, and debugging is harder, with fewer tools.",
      "Chaque octet compte : peu ou pas d'allocation dynamique, donc la mémoire est planifiée à l'avance, souvent avec des tampons statiques. On surveille la taille de la pile, on choisit de petits types entiers, on évite les bibliothèques lourdes et les flottants quand la puce n'a pas d'unité de calcul flottant, et on mesure la taille du code. La consommation d'énergie et les contraintes de temps comptent aussi, et le débogage est plus difficile, avec moins d'outils.",
    ],
    [
      "rtos", "compare",
      "What does an RTOS bring compared with a simple main loop?",
      "Qu'apporte un RTOS par rapport à une simple boucle principale (super-loop) ?",
      "A main loop runs every task in turn: it is simple, but timing is hard to guarantee when one task is slow. An RTOS provides tasks with priorities and a scheduler, so an urgent task can interrupt a less important one, plus queues, semaphores and timers to coordinate them. You gain predictability for real-time systems, at the cost of memory and complexity.",
      "Une boucle principale exécute chaque tâche à tour de rôle : c'est simple, mais le timing devient difficile à garantir quand une tâche est lente. Un RTOS fournit des tâches avec des priorités et un ordonnanceur, pour qu'une tâche urgente puisse interrompre une tâche moins importante, ainsi que des files, des sémaphores et des timers pour les coordonner. On gagne en prévisibilité pour les systèmes temps réel, au prix de mémoire et de complexité.",
    ],
    [
      "resets", "troubleshoot",
      "Your firmware sometimes resets on its own. Where do you start looking?",
      "{Votre|Ton} firmware redémarre parfois tout seul. Par où {commencez-vous|commences-tu} à chercher ?",
      "I first read the register that records the reset cause: watchdog, brown-out from a weak power supply, or a hard fault. A watchdog reset points to a task that is stuck or too slow; a hard fault points to a stack overflow, a bad pointer or an unaligned access, and the fault registers give the address involved. I also check the power supply, and add logs or a debugger to see what runs just before.",
      "Je commence par lire le registre qui indique la cause du redémarrage : watchdog, brown-out dû à une alimentation faible, ou hard fault. Un reset du watchdog oriente vers une tâche bloquée ou trop lente ; un hard fault vers un dépassement de pile, un mauvais pointeur ou un accès non aligné, et les registres de faute donnent l'adresse en cause. Je vérifie aussi l'alimentation, et j'ajoute des logs ou un débogueur pour voir ce qui s'exécute juste avant.",
    ],
  ],
);
